import {
  Bell,
  Brain,
  BrainCircuit,
  BriefcaseBusiness,
  Code2,
  FileText,
  Film,
  FolderKanban,
  Images,
  LayoutDashboard,
  MapPinned,
  Mic2,
  Settings2,
  Sparkles,
  UserCircle,
  Wand2,
} from 'lucide-react';

export const MODULE_REGISTRY = [
  {
    id: 'control',
    name: 'Control Center',
    route: '/studio/dashboard',
    icon: LayoutDashboard,
    status: 'ready',
    completion: 85,
    visible: true,
    navigationOrder: 1,
  },
  {
    id: 'advisor',
    name: 'Executive Advisor',
    route: '/studio/advisor',
    icon: BrainCircuit,
    status: 'ready',
    completion: 85,
    visible: true,
    navigationOrder: 2,
  },
  {
    id: 'mentor',
    name: 'Mentor',
    route: '/studio/mentor',
    icon: Brain,
    status: 'ready',
    completion: 90,
    visible: true,
    navigationOrder: 3,
  },
  {
    id: 'drive',
    name: 'LUMINA Drive',
    route: '/studio/drive',
    icon: MapPinned,
    status: 'ready',
    completion: 90,
    visible: true,
    navigationOrder: 4,
  },
  {
    id: 'code-builder',
    name: 'Code Builder',
    route: '/studio/code-builder',
    icon: Code2,
    status: 'ready',
    completion: 90,
    visible: true,
    navigationOrder: 5,
  },
  {
    id: 'developer',
    name: 'Developer Center',
    route: '/studio/developer',
    icon: Code2,
    status: 'legacy',
    completion: 85,
    visible: false,
    navigationOrder: 99,
  },
  {
    id: 'image',
    name: 'Image Studio',
    route: '/studio/generate',
    icon: Sparkles,
    status: 'ready',
    completion: 85,
    providers: ['image'],
    visible: true,
    navigationOrder: 6,
  },
  {
    id: 'editor',
    name: 'AI Image Editor',
    route: '/studio/editor',
    icon: Wand2,
    status: 'ready',
    completion: 85,
    visible: true,
    navigationOrder: 7,
  },
  {
    id: 'video',
    name: 'Video Studio',
    route: '/studio/video-studio',
    icon: Film,
    status: 'ready',
    completion: 80,
    providers: ['video'],
    visible: true,
    navigationOrder: 8,
  },
  {
    id: 'voice',
    name: 'Voice Studio',
    route: '/studio/voice-studio',
    icon: Mic2,
    status: 'ready',
    completion: 70,
    providers: ['voice'],
    visible: true,
    navigationOrder: 9,
  },
  {
    id: 'identity',
    name: 'Identity Packs',
    route: '/studio/identity',
    icon: UserCircle,
    status: 'ready',
    completion: 85,
    visible: true,
    navigationOrder: 10,
  },
  {
    id: 'documents',
    name: 'Documents',
    route: '/studio/documents',
    icon: FileText,
    status: 'ready',
    completion: 100,
    visible: true,
    navigationOrder: 11,
  },
  {
    id: 'gallery',
    name: 'Media Library',
    route: '/studio/media-library',
    icon: Images,
    status: 'ready',
    completion: 70,
    visible: true,
    navigationOrder: 12,
  },
  {
    id: 'jobs',
    name: 'Jobs Center',
    route: '/studio/jobs',
    icon: BriefcaseBusiness,
    status: 'ready',
    completion: 65,
    visible: true,
    navigationOrder: 13,
  },
  {
    id: 'notifications',
    name: 'Notifications',
    route: '/studio/notifications',
    icon: Bell,
    status: 'ready',
    completion: 60,
    visible: true,
    navigationOrder: 14,
  },
  {
    id: 'projects',
    name: 'Projects',
    route: '/studio/projects',
    icon: FolderKanban,
    status: 'ready',
    completion: 55,
    visible: true,
    navigationOrder: 15,
  },
  {
    id: 'settings',
    name: 'Settings',
    route: '/studio/settings',
    icon: Settings2,
    status: 'ready',
    completion: 55,
    visible: true,
    navigationOrder: 16,
  },
];

export const navigationModules = () =>
  MODULE_REGISTRY
    .filter((item) => item.visible)
    .sort((a, b) => a.navigationOrder - b.navigationOrder);
