const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={map:null,userMarker:null,routeLayer:null,poiLayer:null,lastPos:null,startAt:null,totalM:0,speeds:[],route:null,watchId:null,alerts:new Map(),spoken:new Set(),freeDrive:false};
const cfg={nominatim:'https://nominatim.openstreetmap.org',osrm:'https://router.project-osrm.org',overpass:'https://overpass-api.de/api/interpreter'};
function kmh(ms){return Number.isFinite(ms)?Math.max(0,ms*3.6):0}function dist(a,b){const R=6371e3,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180;const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}function fmtTime(ms){const m=Math.floor(ms/60000);return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function speak(t){if(!('speechSynthesis'in window)||!t)return;const u=new SpeechSynthesisUtterance(t);u.lang='el-GR';u.rate=.96;speechSynthesis.cancel();speechSynthesis.speak(u)}
function addAlert(id,icon,title,detail,voice){state.alerts.set(id,{icon,title,detail});renderAlerts();if(voice&&!state.spoken.has(id)){state.spoken.add(id);speak(voice)}}function clearAlert(id){state.alerts.delete(id);renderAlerts()}function renderAlerts(){const el=$('#alertsList'),arr=[...state.alerts.values()];$('#alertCount').textContent=`${arr.length} ειδοποιήσεις`;el.innerHTML=arr.length?arr.map(a=>`<div class="alert"><span>${a.icon}</span><div><b>${a.title}</b><small>${a.detail||''}</small></div></div>`).join(''):'<div class="empty">Δεν υπάρχουν ενεργές ειδοποιήσεις.</div>'}
function initMap(){state.map=L.map('map',{zoomControl:false}).setView([39.0742,21.8243],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(state.map);L.control.zoom({position:'bottomright'}).addTo(state.map)}
function startGPS(){if(!navigator.geolocation){$('#gpsStatus').textContent='GPS μη διαθέσιμο';return}state.startAt=Date.now();state.watchId=navigator.geolocation.watchPosition(onPos,e=>{$('#gpsStatus').textContent='GPS error';addAlert('gps','📡','GPS','Ενεργοποίησε την άδεια τοποθεσίας.')},{enableHighAccuracy:true,maximumAge:1500,timeout:12000})}
async function onPos(p){const c={lat:p.coords.latitude,lng:p.coords.longitude};const sp=kmh(p.coords.speed);$('#speed').textContent=Math.round(sp);state.speeds.push(sp);if(state.speeds.length>120)state.speeds.shift();if(state.lastPos){const d=dist(state.lastPos,c);if(d<500)state.totalM+=d}state.lastPos=c;$('#tripDistance').textContent=`${(state.totalM/1000).toFixed(1)} km`;$('#tripTime').textContent=fmtTime(Date.now()-state.startAt);$('#avgSpeed').textContent=`${Math.round(state.speeds.reduce((a,b)=>a+b,0)/Math.max(1,state.speeds.length))} km/h`;$('#gpsStatus').textContent=`GPS ±${Math.round(p.coords.accuracy)}m`;if(!state.userMarker){state.userMarker=L.circleMarker(c,{radius:8,weight:4,color:'#fff',fillColor:'#4fd1c5',fillOpacity:1}).addTo(state.map);state.map.setView(c,16)}else state.userMarker.setLatLng(c);if(state.freeDrive||state.route)state.map.panTo(c,{animate:true});checkOverspeed(sp);checkRouteProgress(c);throttledRoadIntel(c)}
function checkOverspeed(sp){const lim=parseInt($('#speedLimit').textContent);if(Number.isFinite(lim)&&sp>lim+4)addAlert('speed','⚠️','Υπέρβαση ορίου',`${Math.round(sp)} km/h σε όριο ${lim}`,'Προσοχή. Έχεις υπερβεί το όριο ταχύτητας.');else clearAlert('speed')}
let intelTimer=0;function throttledRoadIntel(c){if(Date.now()-intelTimer<18000)return;intelTimer=Date.now();reverseRoad(c);queryRoadFeatures(c)}
async function reverseRoad(c){try{const r=await fetch(`${cfg.nominatim}/reverse?format=jsonv2&lat=${c.lat}&lon=${c.lng}&zoom=18&addressdetails=1`,{headers:{'Accept':'application/json'}});const j=await r.json();$('#roadName').textContent=j.address?.road||j.display_name?.split(',')[0]||'—'}catch{}}
async function queryRoadFeatures(c){const q=`[out:json][timeout:10];(node(around:900,${c.lat},${c.lng})[highway=speed_camera];way(around:80,${c.lat},${c.lng})[highway][maxspeed];);out tags center;`;try{const r=await fetch(cfg.overpass,{method:'POST',body:q});const j=await r.json();const cam=j.elements.filter(x=>x.tags?.highway==='speed_camera');const road=j.elements.find(x=>x.tags?.maxspeed);if(road){const n=parseInt(String(road.tags.maxspeed).match(/\d+/)?.[0]);if(n)$('#speedLimit').textContent=n}if(cam.length)addAlert('camera','📷','Κάμερα ταχύτητας',`Εντοπίστηκαν ${cam.length} καταχωρημένα σημεία σε ακτίνα ~900m.`,'Προσοχή. Καταχωρημένη κάμερα ταχύτητας στην περιοχή.');else clearAlert('camera')}catch{}}
async function geocode(q){const r=await fetch(`${cfg.nominatim}/search?format=jsonv2&limit=6&countrycodes=gr&q=${encodeURIComponent(q)}`);return await r.json()}
async function routeToQuery(q){if(!state.lastPos){addAlert('waitgps','📡','Περιμένω GPS','Χρειάζεται τρέχουσα θέση.');return}try{const g=await geocode(q);if(!g.length){addAlert('dest','🔎','Δεν βρέθηκε προορισμός',q);return}clearAlert('dest');const d={lat:+g[0].lat,lng:+g[0].lon,name:g[0].display_name};await routeTo(d)}catch{addAlert('routeerr','⚠️','Σφάλμα διαδρομής','Δοκίμασε ξανά όταν υπάρχει σύνδεση δεδομένων.')}}
async function routeTo(d){const o=state.lastPos;const url=`${cfg.osrm}/route/v1/driving/${o.lng},${o.lat};${d.lng},${d.lat}?overview=full&geometries=geojson&steps=true`;const r=await fetch(url);const j=await r.json();if(j.code!=='Ok')throw Error('route');state.route=j.routes[0];if(state.routeLayer)state.routeLayer.remove();state.routeLayer=L.geoJSON(state.route.geometry,{style:{color:'#4fd1c5',weight:6,opacity:.9}}).addTo(state.map);state.map.fitBounds(state.routeLayer.getBounds(),{padding:[30,30]});L.marker(d).addTo(state.map).bindPopup(d.name);const leg=state.route.legs[0];$('#maneuverCard').classList.remove('hidden');$('#maneuverText').textContent=leg.steps[0]?.maneuver?.instruction||leg.steps[0]?.name||'Ξεκίνα τη διαδρομή';$('#maneuverDistance').textContent=`${(state.route.distance/1000).toFixed(1)} km`;speak(`Η διαδρομή ξεκίνησε. Απόσταση ${(state.route.distance/1000).toFixed(1)} χιλιόμετρα.`);detectRouteCurves(state.route.geometry.coordinates)}
function detectRouteCurves(coords){let sharp=0;for(let i=2;i<coords.length;i+=3){const a=coords[i-2],b=coords[i-1],c=coords[i];const h1=Math.atan2(b[1]-a[1],b[0]-a[0]),h2=Math.atan2(c[1]-b[1],c[0]-b[0]);let d=Math.abs((h2-h1)*180/Math.PI);if(d>180)d=360-d;if(d>55)sharp++}if(sharp)addAlert('curves','↪️','Έντονες στροφές',`${sharp} έντονες αλλαγές κατεύθυνσης στη χαρτογραφημένη διαδρομή.`)}
function checkRouteProgress(c){if(!state.route)return;const steps=state.route.legs?.[0]?.steps||[];let best=null;for(const s of steps){const loc=s.maneuver?.location;if(!loc)continue;const d=dist(c,{lat:loc[1],lng:loc[0]});if(!best||d<best.d)best={s,d}}if(best&&best.d<900){$('#maneuverText').textContent=best.s.maneuver?.instruction||best.s.name||'Συνέχισε';$('#maneuverDistance').textContent=best.d<1000?`${Math.round(best.d)} m`:`${(best.d/1000).toFixed(1)} km`;if(best.d<250&&best.d>80){const id='turn-'+best.s.maneuver.location.join(',');if(!state.spoken.has(id)){state.spoken.add(id);speak(`Σε ${Math.round(best.d/10)*10} μέτρα, ${best.s.name||'ακολούθησε την επόμενη οδηγία'}.`)}}}}
const poiTags={pharmacy:['amenity','pharmacy'],fuel:['amenity','fuel'],restaurant:['amenity','restaurant'],gym:['leisure','fitness_centre'],parking:['amenity','parking']};async function findPOI(kind){if(!state.lastPos)return addAlert('waitgps','📡','Περιμένω GPS','Χρειάζεται τρέχουσα θέση.');const [k,v]=poiTags[kind];const c=state.lastPos,q=`[out:json][timeout:15];(node(around:5000,${c.lat},${c.lng})[${k}=${v}];way(around:5000,${c.lat},${c.lng})[${k}=${v}];);out center tags 20;`;try{const r=await fetch(cfg.overpass,{method:'POST',body:q});const j=await r.json();if(state.poiLayer)state.poiLayer.clearLayers();else state.poiLayer=L.layerGroup().addTo(state.map);j.elements.slice(0,20).forEach(x=>{const p=x.lat?{lat:x.lat,lng:x.lon}:{lat:x.center?.lat,lng:x.center?.lon};if(!p.lat)return;const name=x.tags?.name||v;L.marker(p).addTo(state.poiLayer).bindPopup(`<b>${name}</b><br><button class="poi-route" data-lat="${p.lat}" data-lng="${p.lng}" data-name="${name}">Διαδρομή</button>`)});addAlert('poi','📍','Κοντινά σημεία',`${j.elements.length} αποτελέσματα σε ακτίνα 5 km.`)}catch{addAlert('poierr','⚠️','POI προσωρινά μη διαθέσιμα','Η δημόσια υπηρεσία δεδομένων δεν απάντησε.')}}
function setupVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#voiceBtn').disabled=true;$('#voiceHint').textContent='Η φωνητική αναγνώριση δεν υποστηρίζεται σε αυτόν τον browser.';return}const rec=new SR();rec.lang='el-GR';rec.interimResults=false;$('#voiceBtn').addEventListener('click',()=>rec.start());rec.onresult=e=>{const t=e.results[0][0].transcript.toLowerCase();$('#voiceHint').textContent=`Άκουσα: ${t}`;if(t.includes('βενζ'))findPOI('fuel');else if(t.includes('φαρμακ'))findPOI('pharmacy');else if(t.includes('εστια')||t.includes('φαγη'))findPOI('restaurant');else if(t.includes('γυμνα'))findPOI('gym');else{const q=t.replace(/πήγαινέ με|πήγαινε με|διαδρομή για|προς/g,'').trim();if(q)routeToQuery(q)}}}
function renderMonitor(){const checks=[['Leaflet χάρτης',!!window.L],['GPS API','geolocation'in navigator],['Ελληνική TTS','speechSynthesis'in window],['Voice input',!!(window.SpeechRecognition||window.webkitSpeechRecognition)],['Online',navigator.onLine],['Routing engine',true],['POI / OSM',true],['Speed cameras / OSM',true]];$('#monitorGrid').innerHTML=checks.map(([n,v])=>`<div class="monitor-item"><span>${n}</span><b class="${v?'ok':'warn'}">${v?'READY':'LIMITED'}</b></div>`).join('');$('#readyState').textContent=checks.filter(x=>x[1]).length>=6?'OPERATIONAL':'LIMITED'}
$('#themeBtn').addEventListener('click',()=>document.body.classList.toggle('light'));$('#routeBtn').addEventListener('click',()=>routeToQuery($('#destinationInput').value.trim()));$('#destinationInput').addEventListener('keydown',e=>{if(e.key==='Enter')routeToQuery(e.target.value.trim())});$$('[data-poi]').forEach(b=>b.addEventListener('click',()=>findPOI(b.dataset.poi)));$('#freeDriveBtn').addEventListener('click',()=>{state.freeDrive=!state.freeDrive;$('#freeDriveBtn span').textContent=state.freeDrive?'Free Drive ON':'Free Drive';if(state.freeDrive)speak('Λειτουργία ελεύθερης οδήγησης ενεργή.')});document.addEventListener('click',e=>{if(e.target.classList.contains('poi-route'))routeTo({lat:+e.target.dataset.lat,lng:+e.target.dataset.lng,name:e.target.dataset.name})});window.addEventListener('online',renderMonitor);window.addEventListener('offline',renderMonitor);
initMap();setupVoice();renderMonitor();startGPS();