(()=>{
'use strict';
if(!window.L||!L.map||L.map.__luminaWrapped)return;
const original=L.map.bind(L);
const ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.openstreetmap.fr/api/interpreter'];
const wrapped=function(...args){
  const map=original(...args);window.__luminaDriveMap=map;
  map.createPane('roadNames');const pane=map.getPane('roadNames');pane.style.zIndex='475';pane.style.pointerEvents='none';
  const layer=L.layerGroup().addTo(map);let current=null,lastKey='',busy=false,timer=null;
  if(!document.getElementById('lumina-road-label-style')){const s=document.createElement('style');s.id='lumina-road-label-style';s.textContent=`.lumina-road-name.leaflet-tooltip,.lumina-current-road.leaflet-tooltip{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;white-space:nowrap;pointer-events:none;box-shadow:none}.lumina-road-name.leaflet-tooltip{background:rgba(255,255,255,.88);border:1px solid rgba(25,35,50,.13);color:#263445;border-radius:6px;padding:2px 5px;font-size:11px;font-weight:760;text-shadow:0 1px 0 #fff}.lumina-road-name.road-local.leaflet-tooltip{font-size:10.5px;font-weight:680;background:rgba(255,255,255,.78)}.lumina-current-road.leaflet-tooltip{background:rgba(7,17,31,.96);color:#fff;border:1px solid rgba(88,221,209,.55);border-radius:8px;padding:4px 7px;font-size:11.5px;font-weight:800}.lumina-road-name.leaflet-tooltip:before,.lumina-current-road.leaflet-tooltip:before{display:none}`;document.head.appendChild(s)}
  const bestName=t=>t?.['name:el']||t?.name||t?.official_name||t?.loc_name||t?.alt_name||t?.ref||'';
  const updateCurrent=()=>{const marker=window.__luminaCurrentUserMarker,road=document.getElementById('roadName')?.textContent?.trim();if(!marker||!road||road==='—')return;const ll=marker.getLatLng?.();if(!ll)return;if(current)layer.removeLayer(current);current=L.circleMarker(ll,{pane:'roadNames',radius:1,opacity:0,fillOpacity:0,interactive:false}).addTo(layer);current.bindTooltip(road,{permanent:true,direction:'top',offset:[0,-14],className:'lumina-current-road',opacity:1})};
  async function fetchRoads(q){let last;for(const ep of ENDPOINTS){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),14000);const r=await fetch(ep,{method:'POST',body:q,signal:c.signal,headers:{'Content-Type':'text/plain;charset=UTF-8'}});clearTimeout(t);if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){last=e}}throw last||new Error('roads-unavailable')}
  const mid=g=>Array.isArray(g)&&g.length?g[Math.floor((g.length-1)/2)]:null;
  async function load(){const z=map.getZoom();if(z<12||busy){if(z<12){layer.clearLayers();current=null;lastKey=''}return}const b=map.getBounds().pad(.18),c=b.getCenter(),key=`${z}:${c.lat.toFixed(3)}:${c.lng.toFixed(3)}`;if(key===lastKey){updateCurrent();return}busy=true;try{const q=`[out:json][timeout:14];way(${b.getSouth()},${b.getWest()},${b.getNorth()},${b.getEast()})[highway][name];out tags geom 420;`;const j=await fetchRoads(q);layer.clearLayers();current=null;const rank={motorway:0,trunk:1,primary:2,secondary:3,tertiary:4,residential:5,living_street:6,unclassified:6,service:7,pedestrian:8};const rows=[];for(const w of j.elements||[]){const name=bestName(w.tags),p=mid(w.geometry);if(!name||!p||!Number.isFinite(p.lat)||!Number.isFinite(p.lon))continue;const ref=w.tags?.ref,label=ref&&!name.includes(ref)?`${name} · ${ref}`:name;rows.push({label,ll:[p.lat,p.lon],type:w.tags?.highway||'',d:map.distance(c,L.latLng(p.lat,p.lon))})}rows.sort((a,b)=>(rank[a.type]??9)-(rank[b.type]??9)||a.d-b.d);const used=[],seen=new Set(),spacing=z>=18?16:z>=17?24:z>=16?34:z>=15?46:z>=14?62:82,limit=z>=18?180:z>=17?140:z>=16?100:z>=15?72:z>=14?48:30;for(const x of rows){const n=x.label.toLocaleLowerCase('el-GR');if(seen.has(n)&&z<17)continue;if(used.some(p=>map.distance(L.latLng(x.ll[0],x.ll[1]),L.latLng(p[0],p[1]))<spacing))continue;seen.add(n);used.push(x.ll);const local=['residential','living_street','service','unclassified','pedestrian'].includes(x.type);const m=L.circleMarker(x.ll,{pane:'roadNames',radius:1,opacity:0,fillOpacity:0,interactive:false}).addTo(layer);m.bindTooltip(x.label,{permanent:true,direction:'center',className:`lumina-road-name ${local?'road-local':''}`,opacity:1});if(used.length>=limit)break}lastKey=key}catch(e){console.warn('[LUMINA road labels]',e)}finally{busy=false;updateCurrent()}}
  const schedule=()=>{clearTimeout(timer);timer=setTimeout(load,180)};map.on('zoomend moveend',schedule);map.whenReady(schedule);const roadEl=document.getElementById('roadName');if(roadEl)new MutationObserver(()=>setTimeout(updateCurrent,0)).observe(roadEl,{childList:true,characterData:true,subtree:true});return map;
};
Object.assign(wrapped,L.map);wrapped.__luminaWrapped=true;L.map=wrapped;
})();
