(()=>{
  if(!window.L||!L.map||L.map.__luminaWrapped)return;
  const originalMap=L.map.bind(L);
  const ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.openstreetmap.fr/api/interpreter','https://overpass.private.coffee/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter'];
  const wrappedMap=function(...args){
    const map=originalMap(...args);window.__luminaDriveMap=map;
    map.createPane('roadNames');const pane=map.getPane('roadNames');pane.style.zIndex='470';pane.style.pointerEvents='none';
    const labelsLayer=L.layerGroup([],{pane:'roadNames'}).addTo(map);let currentRoadLabel=null,lastKey='',loading=false,timer=null;
    if(!document.getElementById('lumina-road-label-style')){const style=document.createElement('style');style.id='lumina-road-label-style';style.textContent=`
      .lumina-road-name.leaflet-tooltip,.lumina-current-road.leaflet-tooltip{font-family:Inter,-apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",Roboto,Arial,sans-serif;font-weight:650;letter-spacing:-.015em;line-height:1.05;white-space:nowrap;pointer-events:none;text-shadow:0 1px 0 rgba(255,255,255,.95),0 0 3px rgba(255,255,255,.9);box-shadow:none}
      .lumina-road-name.leaflet-tooltip{background:rgba(255,255,255,.72);border:1px solid rgba(38,52,70,.10);color:#344255;border-radius:6px;padding:2px 5px;font-size:10.5px}
      .lumina-road-name.road-major.leaflet-tooltip{font-size:11.5px;font-weight:760;color:#1f2b3a;background:rgba(255,255,255,.82)}
      .lumina-road-name.road-local.leaflet-tooltip{font-size:10px;font-weight:620;color:#4a5665;background:rgba(255,255,255,.62)}
      .lumina-current-road.leaflet-tooltip{background:rgba(7,17,31,.94);color:#fff;border:1px solid rgba(88,221,209,.5);border-radius:8px;padding:4px 7px;font-size:11.5px;font-weight:760;text-shadow:none;box-shadow:0 3px 10px rgba(0,0,0,.2)}
      .lumina-road-name.leaflet-tooltip:before,.lumina-current-road.leaflet-tooltip:before{display:none}
    `;document.head.appendChild(style)}
    const updateCurrentRoad=()=>{const marker=window.__luminaCurrentUserMarker,road=document.getElementById('roadName')?.textContent?.trim();if(!marker||!road||road==='—')return;const latlng=marker.getLatLng?.();if(!latlng)return;if(currentRoadLabel)labelsLayer.removeLayer(currentRoadLabel);currentRoadLabel=L.circleMarker(latlng,{pane:'roadNames',radius:1,opacity:0,fillOpacity:0,interactive:false}).addTo(labelsLayer);currentRoadLabel.bindTooltip(road,{permanent:true,direction:'top',offset:[0,-14],className:'lumina-current-road',opacity:1})};
    async function fetchRoads(q){let last;for(const ep of ENDPOINTS){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);const r=await fetch(ep,{method:'POST',body:q,signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){last=e}}throw last||new Error('roads')}
    function midpoint(geom){if(!Array.isArray(geom)||!geom.length)return null;const idx=Math.floor((geom.length-1)/2),p=geom[idx];return p&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)?[p.lat,p.lon]:null}
    const loadRoadNames=async()=>{const z=map.getZoom();if(z<13||loading){if(z<13){labelsLayer.clearLayers();currentRoadLabel=null;lastKey=''}return}const b=map.getBounds().pad(.14),c=b.getCenter(),key=`${z}:${c.lat.toFixed(3)}:${c.lng.toFixed(3)}`;if(key===lastKey){updateCurrentRoad();return}loading=true;try{const s=b.getSouth(),w=b.getWest(),n=b.getNorth(),e=b.getEast(),q=`[out:json][timeout:12];way(${s},${w},${n},${e})[highway][name];out tags geom 260;`,j=await fetchRoads(q);labelsLayer.clearLayers();currentRoadLabel=null;const candidates=[];for(const way of j.elements||[]){const name=way.tags?.['name:el']||way.tags?.name,geom=way.geometry;if(!name||!Array.isArray(geom)||geom.length<2)continue;const ref=way.tags?.ref,label=ref&&!name.includes(ref)?`${name} · ${ref}`:name,mid=midpoint(geom);if(!mid)continue;const type=way.tags?.highway||'',d=map.distance(c,L.latLng(mid[0],mid[1]));candidates.push({label,mid,d,type})}const rank={motorway:0,trunk:1,primary:2,secondary:3,tertiary:4,residential:5,living_street:5,unclassified:6,service:7,road:7,pedestrian:8};candidates.sort((a,b)=>a.d-b.d||(rank[a.type]??9)-(rank[b.type]??9));const seen=new Set(),used=[];const spacing=z>=18?18:z>=17?28:z>=16?42:z>=15?58:78;const limit=z>=18?140:z>=17?110:z>=16?82:z>=15?56:34;for(const x of candidates){const keyName=x.label.toLocaleLowerCase('el-GR');if(seen.has(keyName)&&z<17)continue;let tooClose=false;for(const p of used){if(map.distance(L.latLng(x.mid[0],x.mid[1]),L.latLng(p[0],p[1]))<spacing){tooClose=true;break}}if(tooClose)continue;seen.add(keyName);used.push(x.mid);const major=['motorway','trunk','primary','secondary','tertiary'].includes(x.type),local=['residential','living_street','service','unclassified','road','pedestrian'].includes(x.type);const marker=L.circleMarker(x.mid,{pane:'roadNames',radius:1,opacity:0,fillOpacity:0,interactive:false}).addTo(labelsLayer);marker.bindTooltip(x.label,{permanent:true,direction:'center',className:`lumina-road-name ${major?'road-major':local?'road-local':''}`,opacity:1});if(used.length>=limit)break}lastKey=key}catch(e){console.warn('[LUMINA roads]',e)}finally{loading=false;updateCurrentRoad()}};
    const schedule=()=>{clearTimeout(timer);timer=setTimeout(loadRoadNames,220)};map.on('zoomend moveend',schedule);map.whenReady(schedule);const observer=new MutationObserver(()=>setTimeout(updateCurrentRoad,0)),roadEl=document.getElementById('roadName');if(roadEl)observer.observe(roadEl,{childList:true,characterData:true,subtree:true});return map;
  };
  Object.assign(wrappedMap,L.map);wrappedMap.__luminaWrapped=true;L.map=wrappedMap;
})();