(()=>{
'use strict';
const API='https://api.mapbox.com/search/searchbox/v1/forward';
const Q={restaurant:'restaurant',fast_food:'fast food',cafe:'cafe',bar:'bar',ice_cream:'ice cream',bakery:'bakery',hotel:'hotel',apartment:'apartments',guest_house:'guest house',resort:'resort',camp_site:'camping',pharmacy:'pharmacy',hospital:'hospital',clinic:'clinic',doctors:'doctor',fuel:'gas station',parking:'parking',charging:'EV charging station',car_repair:'car repair',supermarket:'supermarket',convenience:'mini market',mall:'shopping mall',bank:'bank',atm:'ATM',police:'police station',post:'post office',gym:'gym',beach:'beach',museum:'museum',attraction:'tourist attraction'};
const token=()=>String(window.__LUMINA_CONFIG__?.mapboxAccessToken||localStorage.getItem('lumina-mapbox-public-token')||'').trim();
const results=()=>document.querySelector('#poiResults');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rad=v=>v*Math.PI/180,dist=(a,b)=>{const R=6371e3,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const fd=m=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`;
async function gps(){const p=window.LuminaGPS?.getLastFix?.(60000)||window.LuminaGPS?.lastFix;if(Number.isFinite(+p?.lat)&&Number.isFinite(+p?.lng))return{lat:+p.lat,lng:+p.lng,accuracy:p.accuracy||null};if(window.LuminaGPS?.getPosition)return window.LuminaGPS.getPosition({maxAge:60000,timeout:7000});throw new Error('gps-unavailable')}
async function search(type,o,key){const u=new URL(API);u.searchParams.set('q',Q[type]||String(type||'').replaceAll('_',' '));u.searchParams.set('access_token',key);u.searchParams.set('language','el');u.searchParams.set('limit','10');u.searchParams.set('proximity',`${o.lng},${o.lat}`);u.searchParams.set('country','GR');u.searchParams.set('types','poi');const c=new AbortController(),timer=setTimeout(()=>c.abort(),10000);try{const r=await fetch(u,{cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{}if(!r.ok){const e=new Error(`HTTP ${r.status}`);e.status=r.status;e.detail=data?.message||text||'';throw e}return(data.features||[]).map(f=>{const p=f.properties||{},c=f.geometry?.coordinates||[],pt={lat:+c[1],lng:+c[0]};if(!Number.isFinite(pt.lat)||!Number.isFinite(pt.lng)||!p.name)return null;const distance=dist(o,pt);if(distance>10000)return null;return{name:p.name,point:pt,distance,area:p.full_address||p.place_formatted||p.address||'Κοντινή περιοχή'}}).filter(Boolean).sort((a,b)=>a.distance-b.distance)}finally{clearTimeout(timer)}}
function render(items,o){const el=results();if(!el)return;if(!items.length){el.innerHTML='<div class="poi-loading">Το Mapbox απάντησε, αλλά δεν βρέθηκαν κοντινά σημεία αυτής της κατηγορίας.</div>';return}el.innerHTML=`<div class="poi-loading"><strong>${items.length} κοντινά σημεία</strong><br><small>Mapbox · ταξινόμηση από το κοντινότερο · GPS${o.accuracy?` ±${Math.round(o.accuracy)}m`:''}</small></div>`+items.map((x,i)=>`<article class="poi-result"><div><strong>${i+1}. ${esc(x.name)}</strong><span>${fd(x.distance)} · ${esc(x.area)}</span></div><button type="button" class="poi-route" data-lat="${x.point.lat}" data-lng="${x.point.lng}" data-name="${esc(x.name)}">▶ Έναρξη</button></article>`).join('')}
async function run(type,key=token()){const el=results();if(!el||!key)return false;el.innerHTML='<div class="poi-loading busy"><span class="poi-spinner"></span><strong>Mapbox: αναζητώ κοντινά σημεία…</strong></div>';try{const o=await gps(),items=await search(type,o,key);render(items,o);return true}catch(e){const status=e?.status?`HTTP ${e.status}`:'σφάλμα δικτύου';el.innerHTML=`<div class="poi-loading error"><strong>Mapbox: ${esc(status)}</strong><br><small>${e?.status===401||e?.status===403?'Το token είναι αποθηκευμένο αλλά δεν επιτρέπεται η χρήση Search Box. Έλεγξε τα δικαιώματα ή τους περιορισμούς URL του token.':'Δεν εμφανίζω εφεδρικά αποτελέσματα όσο υπάρχει Mapbox token.'}</small></div>`;return true}}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-poi-type]'),key=token();if(!b||!key)return;e.preventDefault();e.stopImmediatePropagation();run(b.dataset.poiType,key)},true);
window.LuminaMapboxPOI={run,hasToken:()=>!!token()};
})();
