(()=>{
'use strict';
const NOMINATIM='https://nominatim.openstreetmap.org/search';
const PHOTON='https://photon.komoot.io/api/';
const ARCGIS='https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates';
const MAX_RESULTS=12,DEBOUNCE=450;
const api=window.LuminaNameNavigation=window.LuminaNameNavigation||{map:null,searchMarker:null,selected:null,lastSearchToken:0,lastProviderState:{}};
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('el-GR').replace(/[^a-z0-9α-ω]+/gi,' ').trim();
const stop=new Set(['ο','η','το','τα','της','του','των','σε','στη','στην','στο','και','greece','ελλαδα','ελλαδας']);
const rad=v=>v*Math.PI/180;
const distance=(a,b)=>{if(!a||!b)return null;const R=6371e3,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const withTimeout=(p,ms,label)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error(label||'timeout')),ms))]);
function captureMap(){if(!window.L||typeof L.map!=='function'||L.map.__luminaSearchWrapped)return;const original=L.map;function wrapped(...args){const m=original.apply(this,args);api.map=m;return m}Object.assign(wrapped,original);wrapped.__luminaSearchWrapped=true;L.map=wrapped}captureMap();
function currentPos(){const f=window.LuminaGPS?.getLastFix?.(60000);if(f)return{lat:f.lat,lng:f.lng};try{const p=window.__luminaCurrentUserMarker?.getLatLng?.();if(Number.isFinite(p?.lat)&&Number.isFinite(p?.lng))return{lat:p.lat,lng:p.lng}}catch{}return null}
function addr(p){if(p.__addr)return p.__addr;const a=p.address||{};const street=[a.road||a.pedestrian||a.residential,a.house_number].filter(Boolean).join(' ');return[street,a.suburb,a.city||a.town||a.village||a.municipality,a.postcode,a.country].filter(Boolean).join(', ')||p.display_name||''}
function name(p){return p.namedetails?.['name:el']||p.namedetails?.name||p.name||String(p.display_name||'Προορισμός').split(',')[0]}
async function getJson(url,timeout=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,mode:'cors',credentials:'omit'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}finally{clearTimeout(t)}}
async function googlePlaces(q){if(!window.LuminaGooglePlaces?.hasKey?.())return[];const items=await withTimeout(window.LuminaGooglePlaces.textSearch(q,null),9000,'google-places-timeout');return items.map(x=>({lat:String(x.lat),lon:String(x.lng),name:x.name,display_name:[x.name,x.address].filter(Boolean).join(', '),__addr:x.address||'',__source:'Google Places',__google:true}))}
async function nominatim(q){const u=new URL(NOMINATIM);u.searchParams.set('format','jsonv2');u.searchParams.set('q',q);u.searchParams.set('countrycodes','gr');u.searchParams.set('limit',String(MAX_RESULTS));u.searchParams.set('addressdetails','1');u.searchParams.set('namedetails','1');u.searchParams.set('dedupe','1');u.searchParams.set('accept-language','el,en');return(await getJson(u,7500)).filter(x=>Number.isFinite(+x.lat)&&Number.isFinite(+x.lon)).map(x=>({...x,__source:'OpenStreetMap'}))}
async function photon(q){const u=new URL(PHOTON);u.searchParams.set('q',q);u.searchParams.set('limit',String(MAX_RESULTS));u.searchParams.set('lang','el');const d=await getJson(u,7500);return(d.features||[]).map(f=>{const pr=f.properties||{},c=f.geometry?.coordinates||[],lat=+c[1],lon=+c[0];if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;const street=[pr.street,pr.housenumber].filter(Boolean).join(' '),locality=pr.city||pr.town||pr.village||pr.county||pr.state;return{lat:String(lat),lon:String(lon),name:pr.name||street||locality||'Προορισμός',display_name:[pr.name||street,locality,pr.state,pr.country].filter(Boolean).join(', '),__addr:[street,locality,pr.postcode,pr.country].filter(Boolean).join(', '),__source:'Photon'}}).filter(Boolean)}
async function arcgis(q){const u=new URL(ARCGIS);u.searchParams.set('f','json');u.searchParams.set('SingleLine',q);u.searchParams.set('countryCode','GRC');u.searchParams.set('maxLocations',String(MAX_RESULTS));u.searchParams.set('outFields','Match_addr,Addr_type,PlaceName,City,Region,Postal,Country');const d=await getJson(u,8000);return(d.candidates||[]).map(x=>{const lat=+x.location?.y,lon=+x.location?.x;if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;const a=x.attributes||{},label=x.address||a.Match_addr||q;return{lat:String(lat),lon:String(lon),name:a.PlaceName||String(label).split(',')[0]||q,display_name:label,__addr:label,__source:'ArcGIS',__arcgis:true,__score:Number(x.score)||0}}).filter(Boolean)}
function features(q){const n=norm(q),tokens=n.split(' ').filter(t=>t.length>1&&!stop.has(t)),number=(n.match(/\b\d+[a-zα-ω]?\b/i)||[])[0]||null;return{n,tokens,number}}
function assess(p,q){const f=features(q),label=norm(`${name(p)} ${addr(p)} ${p.display_name||''}`),matches=f.tokens.filter(t=>label.includes(t)),ratio=f.tokens.length?matches.length/f.tokens.length:0;let score=ratio*100;if(label.includes(f.n))score+=45;if(p.__google)score+=35;if(p.__arcgis)score+=Math.min(20,(p.__score||0)/5);if(f.number){if(new RegExp(`\\b${f.number}\\b`,'i').test(label))score+=55;else score-=85}const pos=currentPos(),d=distance(pos,{lat:+p.lat,lng:+p.lon});if(Number.isFinite(d))score+=Math.max(0,8-Math.min(8,d/100000));const safe=(!f.number||new RegExp(`\\b${f.number}\\b`,'i').test(label))&&ratio>=(f.tokens.length>=3?.6:.5);return{score,safe,ratio,matches,d}}
function merge(groups,q){const items=[];for(const p of groups.flat()){if(!p||!Number.isFinite(+p.lat)||!Number.isFinite(+p.lon))continue;const a=assess(p,q);const duplicate=items.find(x=>distance({lat:+x.lat,lng:+x.lon},{lat:+p.lat,lng:+p.lon})<35&&norm(name(x))===norm(name(p)));if(duplicate){if(a.score>(duplicate.__assessment?.score||0)){Object.assign(duplicate,p,{__assessment:a})}continue}items.push({...p,__assessment:a})}return items.sort((a,b)=>b.__assessment.score-a.__assessment.score).slice(0,MAX_RESULTS)}
async function provider(label,fn){try{const value=await fn();api.lastProviderState[label]={ok:true,count:value.length};return value}catch(e){api.lastProviderState[label]={ok:false,error:String(e?.message||e)};console.warn(`[LUMINA search ${label}]`,e);return[]}}
async function fetchPlaces(q,token){await window.LuminaGPS?.getPosition?.({maxAge:60000,timeout:1500}).catch(()=>null);const tasks=[];if(window.LuminaGooglePlaces?.hasKey?.())tasks.push(provider('Google',()=>googlePlaces(q)));tasks.push(provider('ArcGIS',()=>arcgis(q)));tasks.push(provider('Nominatim',()=>nominatim(q)));tasks.push(provider('Photon',()=>photon(q)));const groups=await Promise.all(tasks);if(token!==api.lastSearchToken)return[];const merged=merge(groups,q);if(merged.length)return merged;const anyResponded=Object.values(api.lastProviderState).some(x=>x?.ok);if(!anyResponded)throw new Error('all-search-providers-failed');return[]}
function panel(){let p=$('#nameSearchResults');if(p)return p;const row=$('.search-row');if(!row)return null;p=document.createElement('section');p.id='nameSearchResults';p.className='name-search-results hidden pretrip-ui';p.setAttribute('aria-live','polite');row.insertAdjacentElement('afterend',p);return p}
function showMarker(p){if(!api.map||!window.L)return;const lat=+p.lat,lng=+p.lon;if(api.searchMarker)try{api.map.removeLayer(api.searchMarker)}catch{}api.searchMarker=L.marker([lat,lng]).addTo(api.map).bindPopup(`<strong>${esc(name(p))}</strong><br>${esc(addr(p))}`);api.map.setView([lat,lng],Math.max(api.map.getZoom?.()||15,16));api.searchMarker.openPopup()}
function render(items,q){const p=panel();if(!p)return;p.__places=items;p.classList.remove('hidden');if(!items.length){p.innerHTML=`<div class="name-search-empty">Δεν βρέθηκε αξιόπιστο αποτέλεσμα για «${esc(q)}». Δοκίμασε να προσθέσεις πόλη ή ΤΚ.</div>`;return}p.innerHTML=items.map((x,i)=>{const a=x.__assessment||{},warning=a.safe?'':'<span><b>Έλεγχος:</b> χρειάζεται πιο συγκεκριμένη περιγραφή πριν ξεκινήσει πλοήγηση.</span>',source=x.__source?`<span><b>Πηγή:</b> ${esc(x.__source)}</span>`:'';return `<article class="name-search-card"><button type="button" class="name-search-main" data-select-search="${i}"><strong>${esc(name(x))}</strong><span><b>Διεύθυνση:</b> ${esc(addr(x))}</span>${Number.isFinite(a.d)?`<span><b>Απόσταση:</b> ${(a.d/1000).toFixed(1)} km</span>`:''}${source}${warning}</button><button type="button" class="name-search-start" data-start-search="${i}" ${a.safe?'':'disabled aria-disabled="true"'}>▶ Έναρξη</button></article>`}).join('')}
async function search(q){const p=panel(),clean=String(q||'').trim();if(!p)return;if(clean.length<2){p.classList.add('hidden');return}const token=++api.lastSearchToken;p.classList.remove('hidden');api.lastProviderState={};p.innerHTML='<div class="name-search-loading"><span class="search-spinner"></span> Αναζήτηση σε πολλαπλές υπηρεσίες…</div>';try{const items=await fetchPlaces(clean,token);if(token===api.lastSearchToken)render(items,clean)}catch(e){console.error('[LUMINA search]',e);if(token===api.lastSearchToken)p.innerHTML='<div class="name-search-empty">Οι υπηρεσίες αναζήτησης δεν απάντησαν. Έλεγξε τη σύνδεση και δοκίμασε ξανά.</div>'}}
function start(p){if(!p?.__assessment?.safe)return;api.selected=p;showMarker(p);const input=$('#destinationInput'),btn=$('#routeBtn');if(!input||!btn)return;input.value=p.display_name||`${name(p)}, ${addr(p)}`;panel()?.classList.add('hidden');btn.dataset.luminaConfirmed='1';btn.dataset.luminaLat=String(p.lat);btn.dataset.luminaLng=String(p.lon);btn.dataset.luminaName=name(p);btn.click();delete btn.dataset.luminaConfirmed}
function bind(){const input=$('#destinationInput'),btn=$('#routeBtn'),p=panel();if(!input||!p)return;input.placeholder='Αναζήτηση με όνομα ή διεύθυνση…';if(btn)btn.textContent='Αναζήτηση';let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value),DEBOUNCE)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();search(input.value)}},true);btn?.addEventListener('click',e=>{if(btn.dataset.luminaConfirmed==='1')return;e.preventDefault();e.stopImmediatePropagation();search(input.value)},true);document.addEventListener('click',e=>{const sb=e.target.closest?.('[data-select-search]'),st=e.target.closest?.('[data-start-search]');if(sb||st){const b=sb||st,x=p.__places?.[+(sb?b.dataset.selectSearch:b.dataset.startSearch)];if(!x)return;showMarker(x);input.value=x.display_name||`${name(x)}, ${addr(x)}`;if(st)start(x);return}if(!e.target.closest?.('.search-row')&&!e.target.closest?.('#nameSearchResults'))p.classList.add('hidden')})}
window.LuminaNameNavigation.search=search;
window.LuminaNameNavigation.getProviderState=()=>({...api.lastProviderState});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();