(()=>{
'use strict';
const NOMINATIM='https://nominatim.openstreetmap.org/search';
const PHOTON='https://photon.komoot.io/api/';
const MAX_RESULTS=12,DEBOUNCE=450;
const api=window.LuminaNameNavigation=window.LuminaNameNavigation||{map:null,searchMarker:null,selected:null,lastSearchToken:0};
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('el-GR').replace(/[^a-z0-9α-ω]+/gi,' ').trim();
const stop=new Set(['ο','η','το','τα','της','του','των','σε','στη','στην','στο','και','greece','ελλαδα','ελλαδας']);
const rad=v=>v*Math.PI/180;
const distance=(a,b)=>{if(!a||!b)return null;const R=6371e3,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
function captureMap(){if(!window.L||typeof L.map!=='function'||L.map.__luminaSearchWrapped)return;const original=L.map;function wrapped(...args){const m=original.apply(this,args);api.map=m;return m}Object.assign(wrapped,original);wrapped.__luminaSearchWrapped=true;L.map=wrapped}captureMap();
function currentPos(){const f=window.LuminaGPS?.getLastFix?.(60000);if(f)return{lat:f.lat,lng:f.lng};try{const p=window.__luminaCurrentUserMarker?.getLatLng?.();if(Number.isFinite(p?.lat)&&Number.isFinite(p?.lng))return{lat:p.lat,lng:p.lng}}catch{}return null}
function addr(p){if(p.__addr)return p.__addr;const a=p.address||{};const street=[a.road||a.pedestrian||a.residential,a.house_number].filter(Boolean).join(' ');return[street,a.suburb,a.city||a.town||a.village||a.municipality,a.postcode,a.country].filter(Boolean).join(', ')||p.display_name||''}
function name(p){return p.namedetails?.['name:el']||p.namedetails?.name||p.name||String(p.display_name||'Προορισμός').split(',')[0]}
async function getJson(url,timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}finally{clearTimeout(t)}}
async function nominatim(q){const u=new URL(NOMINATIM);u.searchParams.set('format','jsonv2');u.searchParams.set('q',q);u.searchParams.set('countrycodes','gr');u.searchParams.set('limit',String(MAX_RESULTS));u.searchParams.set('addressdetails','1');u.searchParams.set('namedetails','1');u.searchParams.set('dedupe','1');u.searchParams.set('accept-language','el,en');const p=currentPos();if(p){u.searchParams.set('viewbox',`${p.lng-2.5},${p.lat+2},${p.lng+2.5},${p.lat-2}`);u.searchParams.set('bounded','0')}return (await getJson(u)).filter(x=>Number.isFinite(+x.lat)&&Number.isFinite(+x.lon)).map(x=>({...x,__source:'Nominatim'}))}
async function photon(q){const u=new URL(PHOTON);u.searchParams.set('q',q);u.searchParams.set('limit',String(MAX_RESULTS));u.searchParams.set('lang','el');const p=currentPos();if(p){u.searchParams.set('lat',p.lat);u.searchParams.set('lon',p.lng)}const d=await getJson(u);return(d.features||[]).map(f=>{const pr=f.properties||{},c=f.geometry?.coordinates||[],lat=+c[1],lon=+c[0];if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;const street=[pr.street,pr.housenumber].filter(Boolean).join(' '),locality=pr.city||pr.town||pr.village||pr.county||pr.state;return{lat:String(lat),lon:String(lon),name:pr.name||street||locality||'Προορισμός',display_name:[pr.name||street,locality,pr.state,pr.country].filter(Boolean).join(', '),__addr:[street,locality,pr.postcode,pr.country].filter(Boolean).join(', '),__source:'Photon'}}).filter(Boolean)}
function features(q){const n=norm(q),tokens=n.split(' ').filter(t=>t.length>1&&!stop.has(t)),number=(n.match(/\b\d+[a-zα-ω]?\b/i)||[])[0]||null;return{n,tokens,number}}
function assess(p,q){const f=features(q),label=norm(`${name(p)} ${addr(p)} ${p.display_name||''}`),matches=f.tokens.filter(t=>label.includes(t)),ratio=f.tokens.length?matches.length/f.tokens.length:0;let score=ratio*100;if(label.includes(f.n))score+=45;if(f.number){if(new RegExp(`\\b${f.number}\\b`,'i').test(label))score+=55;else score-=85}const pos=currentPos(),d=distance(pos,{lat:+p.lat,lng:+p.lon});if(Number.isFinite(d))score+=Math.max(0,20-Math.min(20,d/50000));const safe=(!f.number||new RegExp(`\\b${f.number}\\b`,'i').test(label))&&ratio>=(f.tokens.length>=3?.66:.5);return{score,safe,ratio,matches,d}}
function merge(groups,q){const seen=new Set(),items=[];for(const p of groups.flat()){const k=`${(+p.lat).toFixed(5)}|${(+p.lon).toFixed(5)}|${norm(name(p))}`;if(seen.has(k))continue;seen.add(k);const a=assess(p,q);items.push({...p,__assessment:a})}return items.sort((a,b)=>b.__assessment.score-a.__assessment.score).slice(0,MAX_RESULTS)}
async function fetchPlaces(q,token){await window.LuminaGPS?.getPosition?.({maxAge:60000,timeout:2500}).catch(()=>null);const settled=await Promise.allSettled([nominatim(q),photon(q)]);if(token!==api.lastSearchToken)return[];const ok=settled.filter(x=>x.status==='fulfilled').map(x=>x.value);if(!ok.length)throw new Error('search-providers-failed');return merge(ok,q)}
function panel(){let p=$('#nameSearchResults');if(p)return p;const row=$('.search-row');if(!row)return null;p=document.createElement('section');p.id='nameSearchResults';p.className='name-search-results hidden pretrip-ui';p.setAttribute('aria-live','polite');row.insertAdjacentElement('afterend',p);return p}
function showMarker(p){if(!api.map||!window.L)return;const lat=+p.lat,lng=+p.lon;if(api.searchMarker)try{api.map.removeLayer(api.searchMarker)}catch{}api.searchMarker=L.marker([lat,lng]).addTo(api.map).bindPopup(`<strong>${esc(name(p))}</strong><br>${esc(addr(p))}`);api.map.setView([lat,lng],Math.max(api.map.getZoom?.()||15,16));api.searchMarker.openPopup()}
function render(items,q){const p=panel();if(!p)return;p.__places=items;p.classList.remove('hidden');if(!items.length){p.innerHTML=`<div class="name-search-empty">Δεν βρέθηκε αξιόπιστο αποτέλεσμα για «${esc(q)}». Πρόσθεσε πόλη ή ΤΚ.</div>`;return}p.innerHTML=items.map((x,i)=>{const a=x.__assessment||{},warning=a.safe?'':'<span><b>Έλεγχος:</b> Δεν είναι αρκετά ακριβής αντιστοίχιση για αυτόματη πλοήγηση.</span>';return `<article class="name-search-card"><button type="button" class="name-search-main" data-select-search="${i}"><strong>${esc(name(x))}</strong><span><b>Διεύθυνση:</b> ${esc(addr(x))}</span>${Number.isFinite(a.d)?`<span><b>Απόσταση:</b> ${(a.d/1000).toFixed(1)} km</span>`:''}${warning}</button><button type="button" class="name-search-start" data-start-search="${i}" ${a.safe?'':'disabled aria-disabled="true"'}>▶ Έναρξη</button></article>`}).join('')}
async function search(q){const p=panel(),clean=String(q||'').trim();if(!p)return;if(clean.length<3){p.classList.add('hidden');return}const token=++api.lastSearchToken;p.classList.remove('hidden');p.innerHTML='<div class="name-search-loading"><span class="search-spinner"></span> Αναζητώ ακριβή τοποθεσία…</div>';try{const items=await fetchPlaces(clean,token);if(token===api.lastSearchToken)render(items,clean)}catch(e){console.error('[LUMINA search]',e);if(token===api.lastSearchToken)p.innerHTML='<div class="name-search-empty">Η αναζήτηση δεν απάντησε. Δοκίμασε ξανά.</div>'}}
function start(p){if(!p?.__assessment?.safe)return;api.selected=p;showMarker(p);const input=$('#destinationInput'),btn=$('#routeBtn');if(!input||!btn)return;input.value=p.display_name||`${name(p)}, ${addr(p)}`;panel()?.classList.add('hidden');btn.dataset.luminaConfirmed='1';btn.click();delete btn.dataset.luminaConfirmed}
function bind(){const input=$('#destinationInput'),btn=$('#routeBtn'),p=panel();if(!input||!p)return;input.placeholder='Αναζήτηση με όνομα ή διεύθυνση…';if(btn)btn.textContent='Αναζήτηση';let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value),DEBOUNCE)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search(input.value)}});btn?.addEventListener('click',e=>{if(btn.dataset.luminaConfirmed==='1')return;e.preventDefault();e.stopImmediatePropagation();search(input.value)},true);document.addEventListener('click',e=>{const sb=e.target.closest?.('[data-select-search]'),st=e.target.closest?.('[data-start-search]');if(sb||st){const b=sb||st,x=p.__places?.[+(sb?b.dataset.selectSearch:b.dataset.startSearch)];if(!x)return;showMarker(x);input.value=x.display_name||`${name(x)}, ${addr(x)}`;if(st)start(x);return}if(!e.target.closest?.('.search-row')&&!e.target.closest?.('#nameSearchResults'))p.classList.add('hidden')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
