(()=>{
'use strict';
const $=s=>document.querySelector(s),RADIUS=10000;
const OVERPASS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.openstreetmap.fr/api/interpreter','https://overpass.private.coffee/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter'];
const PHOTON='https://photon.komoot.io/api/';
const drawer=$('#poiDrawer'),cats=$('#poiCategories'),results=$('#poiResults'),title=$('#poiTitle'),back=$('#poiBackBtn');
let lastOrigin=null;
const GROUPS={
 food:{label:'Φαγητό & Ποτό',items:[['restaurant','🍽️ Εστιατόρια / Ταβέρνες'],['fast_food','🥙 Fast food / Σουβλάκι'],['cafe','☕ Καφέ'],['bar','🍸 Bar / Pub'],['ice_cream','🍦 Παγωτό'],['bakery','🥖 Φούρνοι']]},
 stay:{label:'Διαμονή',items:[['hotel','🏨 Ξενοδοχεία'],['apartment','🏠 Apartments / Studios'],['guest_house','🛏️ Guest houses'],['resort','🌴 Resorts'],['camp_site','⛺ Camping']]},
 health:{label:'Υγεία',items:[['pharmacy','💊 Φαρμακεία'],['hospital','🏥 Νοσοκομεία'],['clinic','🩺 Κλινικές'],['doctors','👨‍⚕️ Γιατροί']]},
 car:{label:'Αυτοκίνητο',items:[['fuel','⛽ Βενζινάδικα'],['parking','🅿️ Parking'],['charging','⚡ EV charging'],['car_repair','🔧 Συνεργεία']]},
 shopping:{label:'Αγορές',items:[['supermarket','🛒 Supermarket'],['convenience','🥤 Mini market'],['mall','🏬 Εμπορικά κέντρα']]},
 services:{label:'Υπηρεσίες',items:[['bank','🏦 Τράπεζες'],['atm','💶 ATM'],['police','👮 Αστυνομία'],['post','📮 Ταχυδρομεία']]},
 leisure:{label:'Αναψυχή',items:[['gym','🏋️ Γυμναστήρια'],['beach','🏖️ Παραλίες'],['museum','🏛️ Μουσεία'],['attraction','📸 Αξιοθέατα']]}
};
const TAGS={
 restaurant:[['amenity','restaurant']],fast_food:[['amenity','fast_food']],cafe:[['amenity','cafe'],['shop','coffee']],bar:[['amenity','bar'],['amenity','pub']],ice_cream:[['amenity','ice_cream'],['shop','ice_cream']],bakery:[['shop','bakery']],
 hotel:[['tourism','hotel']],apartment:[['tourism','apartment'],['tourism','chalet'],['tourism','hostel']],guest_house:[['tourism','guest_house']],resort:[['tourism','resort']],camp_site:[['tourism','camp_site']],
 pharmacy:[['amenity','pharmacy']],hospital:[['amenity','hospital']],clinic:[['amenity','clinic']],doctors:[['amenity','doctors']],
 fuel:[['amenity','fuel']],parking:[['amenity','parking']],charging:[['amenity','charging_station']],car_repair:[['shop','car_repair']],
 supermarket:[['shop','supermarket']],convenience:[['shop','convenience']],mall:[['shop','mall']],bank:[['amenity','bank']],atm:[['amenity','atm']],police:[['amenity','police']],post:[['amenity','post_office']],gym:[['leisure','fitness_centre']],beach:[['natural','beach']],museum:[['tourism','museum']],attraction:[['tourism','attraction']]
};
const TERMS={restaurant:['restaurant','taverna','ταβέρνα','εστιατόριο'],fast_food:['souvlaki','σουβλάκι','fast food'],cafe:['cafe','coffee','καφέ'],bar:['bar','pub'],ice_cream:['ice cream','gelato'],bakery:['bakery','φούρνος'],hotel:['hotel'],apartment:['apartments','studios','rooms'],guest_house:['guest house'],resort:['resort'],camp_site:['camping'],pharmacy:['pharmacy'],hospital:['hospital'],clinic:['clinic'],doctors:['doctor'],fuel:['fuel'],parking:['parking'],charging:['charging station'],car_repair:['car repair'],supermarket:['supermarket'],convenience:['mini market'],mall:['shopping mall'],bank:['bank'],atm:['atm'],police:['police'],post:['post office'],gym:['gym'],beach:['beach'],museum:['museum'],attraction:['attraction']};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9α-ω]+/gi,' ').trim();
const rad=v=>v*Math.PI/180,dist=(a,b)=>{const R=6371e3,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const fd=m=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`;
function open(){drawer?.classList.remove('hidden');renderGroups()}function close(){drawer?.classList.add('hidden')}
function renderGroups(){if(!cats||!results)return;title.textContent='Σημεία ενδιαφέροντος';back.classList.add('hidden');results.innerHTML='';cats.innerHTML=Object.entries(GROUPS).map(([k,g])=>`<button class="poi-category" data-poi-group="${k}"><strong>${g.label}</strong><span>${g.items.length} κατηγορίες</span></button>`).join('')}
function renderGroup(k){const g=GROUPS[k];if(!g)return;title.textContent=g.label;back.classList.remove('hidden');cats.innerHTML=g.items.map(([t,l])=>`<button class="poi-item" data-poi-type="${t}">${l}</button>`).join('');results.innerHTML=''}
async function gps(){const shared=window.LuminaGPS?.getLastFix?.(60000);if(shared)return{lat:shared.lat,lng:shared.lng,accuracy:shared.accuracy,source:'shared-gps'};if(window.LuminaGPS?.getPosition)return window.LuminaGPS.getPosition({maxAge:60000,timeout:7000});throw Object.assign(new Error('gps-unavailable'),{kind:'gps-unavailable'})}
async function json(url,opts={},timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...opts,cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}finally{clearTimeout(t)}}
function query(type,o){const clauses=[];for(const [k,v] of TAGS[type]||[])for(const kind of ['node','way','relation'])clauses.push(`${kind}(around:${RADIUS},${o.lat},${o.lng})["${k}"="${v}"];`);return`[out:json][timeout:22];(${clauses.join('')});out center tags;`}
function point(e){if(Number.isFinite(e.lat)&&Number.isFinite(e.lon))return{lat:e.lat,lng:e.lon};if(Number.isFinite(e.center?.lat)&&Number.isFinite(e.center?.lon))return{lat:e.center.lat,lng:e.center.lon};return null}
function fromOverpass(data,o){return(data.elements||[]).map(e=>{const p=point(e),t=e.tags||{};if(!p)return null;const name=t['name:el']||t.name||t.brand||t.operator;if(!name)return null;const d=dist(o,p);if(d>RADIUS)return null;const area=[[t['addr:street'],t['addr:housenumber']].filter(Boolean).join(' '),t['addr:place']||t['addr:city']||t['addr:town']||t['addr:village']].filter(Boolean).join(' · ')||'Κοντινή περιοχή';return{name,point:p,distance:d,area,source:'OpenStreetMap'}}).filter(Boolean)}
async function overpass(type,o){const q=query(type,o);let last;for(const ep of OVERPASS){try{return fromOverpass(await json(`${ep}?data=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}},20000),o)}catch(e){last=e}}throw last||new Error('overpass-failed')}
async function photon(type,o){const accepted=new Set((TAGS[type]||[]).map(([k,v])=>`${k}:${v}`)),out=[];for(const term of (TERMS[type]||[type]).slice(0,4)){try{const u=new URL(PHOTON);u.searchParams.set('q',term);u.searchParams.set('lat',o.lat);u.searchParams.set('lon',o.lng);u.searchParams.set('limit','50');u.searchParams.set('lang','en');const d=await json(u.toString(),{},9000);for(const f of d.features||[]){const pr=f.properties||{},c=f.geometry?.coordinates||[],p={lat:+c[1],lng:+c[0]},key=`${pr.osm_key||''}:${pr.osm_value||''}`;if(!accepted.has(key)||!Number.isFinite(p.lat)||!Number.isFinite(p.lng))continue;const name=pr.name||pr.street||pr.city;if(!name)continue;const di=dist(o,p);if(di>RADIUS)continue;out.push({name,point:p,distance:di,area:[pr.street,pr.city||pr.town||pr.village].filter(Boolean).join(' · ')||'Κοντινή περιοχή',source:'Photon'})}}catch{}}return out}
function merge(groups){const seen=new Set(),out=[];for(const x of groups.flat().sort((a,b)=>a.distance-b.distance)){const k=`${norm(x.name)}|${x.point.lat.toFixed(4)}|${x.point.lng.toFixed(4)}`;if(seen.has(k))continue;seen.add(k);out.push(x)}return out}
function render(items,o){if(!items.length){results.innerHTML='<div class="poi-loading">Το GPS λειτουργεί, οι πάροχοι απάντησαν, αλλά δεν βρέθηκαν καταχωρημένα σημεία αυτής της κατηγορίας έως 10 km.</div>';return}results.innerHTML=`<div class="poi-loading">${items.length} επιβεβαιωμένα σημεία έως 10 km · GPS ${o.accuracy?`±${Math.round(o.accuracy)}m`:'ενεργό'}</div>`+items.slice(0,80).map(x=>`<article class="poi-result"><div><strong>${esc(x.name)}</strong><span>${fd(x.distance)} · ${esc(x.area)}</span></div><button type="button" class="poi-route" data-lat="${x.point.lat}" data-lng="${x.point.lng}" data-name="${esc(x.name)}">▶ Έναρξη</button></article>`).join('')}
async function run(type){if(!results)return;results.innerHTML='<div class="poi-loading busy"><span class="poi-spinner"></span><strong>Χρησιμοποιώ το ενεργό GPS…</strong></div>';let o;try{o=await gps();lastOrigin=o}catch(e){results.innerHTML='<div class="poi-loading error">Δεν υπάρχει πρόσφατη έγκυρη θέση GPS. Αν η ένδειξη GPS επάνω λειτουργεί, περίμενε μία νέα ενημέρωση θέσης και ξαναπάτησε.</div>';return}results.innerHTML='<div class="poi-loading busy"><span class="poi-spinner"></span><strong>Αναζητώ κοντινά σημεία…</strong></div>';const settled=await Promise.allSettled([overpass(type,o),photon(type,o)]),ok=settled.filter(x=>x.status==='fulfilled').map(x=>x.value);if(!ok.length){results.innerHTML='<div class="poi-loading error">Το GPS λειτουργεί, αλλά οι υπηρεσίες κοντινών σημείων δεν απάντησαν. Πρόκειται για πρόβλημα δικτύου/παρόχου, όχι GPS.</div>';return}render(merge(ok),o)}
function route(b){const lat=+b.dataset.lat,lng=+b.dataset.lng;if(!Number.isFinite(lat)||!Number.isFinite(lng))return;drawer?.classList.add('hidden')}
$('#poiOpenBtn')?.addEventListener('click',open);$('#poiCloseBtn')?.addEventListener('click',close);back?.addEventListener('click',renderGroups);cats?.addEventListener('click',e=>{const g=e.target.closest('[data-poi-group]');if(g)return renderGroup(g.dataset.poiGroup);const b=e.target.closest('[data-poi-type]');if(b)run(b.dataset.poiType)});results?.addEventListener('click',e=>{const b=e.target.closest('.poi-route');if(b){e.preventDefault();route(b)}});
})();
