(()=>{
'use strict';
const MAPBOX_API='https://api.mapbox.com/search/searchbox/v1/forward';
const OVERPASS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.openstreetmap.fr/api/interpreter'];
const GROUPS={
  food:{label:'🍽️ Εστίαση',subtitle:'Φαγητό · καφέ · γλυκό · ποτό',maxRadius:30000,minUseful:30,queries:['restaurant','taverna','greek restaurant','seafood restaurant','pizza','pizzeria','italian restaurant','fast food','souvlaki','grill','cafe','coffee','coffee shop','ice cream','gelato','bakery','pastry shop','dessert shop','bar'],osm:[['amenity','restaurant'],['amenity','fast_food'],['amenity','cafe'],['amenity','bar'],['amenity','pub'],['amenity','ice_cream'],['shop','bakery'],['shop','pastry'],['shop','confectionery']]},
  car:{label:'⛽ Αυτοκίνητο',subtitle:'Καύσιμα · συνεργεία · ελαστικά',maxRadius:60000,minUseful:20,queries:['gas station','fuel station','car repair','auto repair','tire shop','tyre shop','auto parts','car wash','EV charging station'],osm:[['amenity','fuel'],['amenity','charging_station'],['shop','car_repair'],['shop','tyres'],['shop','car_parts'],['amenity','car_wash']]},
  health:{label:'🏥 Πρώτες Βοήθειες',subtitle:'Φαρμακεία · νοσοκομεία · κέντρα υγείας',maxRadius:60000,minUseful:20,queries:['pharmacy','hospital','health center','medical center','medical clinic','emergency room','emergency department'],osm:[['amenity','pharmacy'],['amenity','hospital'],['amenity','clinic'],['amenity','doctors'],['healthcare','hospital'],['healthcare','clinic'],['healthcare','centre'],['healthcare','doctor']]},
  shopping:{label:'🛍️ Αγορές',subtitle:'Supermarket · εμπορικά · καταστήματα',maxRadius:30000,minUseful:30,queries:['supermarket','mini market','grocery store','shopping mall','clothing store','shoe store','electronics store','department store','home goods store','hardware store','convenience store'],osm:[['shop','supermarket'],['shop','convenience'],['shop','mall'],['shop','department_store'],['shop','clothes'],['shop','shoes'],['shop','electronics'],['shop','mobile_phone'],['shop','hardware'],['shop','general'],['shop','variety_store'],['shop','greengrocer'],['shop','butcher']]}
};
const RADII=[3000,10000,30000,60000];
const $=s=>document.querySelector(s);
const drawer=$('#poiDrawer'),cats=$('#poiCategories'),results=$('#poiResults'),title=$('#poiTitle'),back=$('#poiBackBtn');
const token=()=>String(window.__LUMINA_CONFIG__?.mapboxAccessToken||localStorage.getItem('lumina-mapbox-public-token')||'').trim();
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('el-GR').replace(/[^a-z0-9α-ω]+/gi,' ').trim();
const rad=v=>v*Math.PI/180;
const distance=(a,b)=>{const R=6371e3,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const fd=m=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`;
async function gps(){const p=window.LuminaGPS?.getLastFix?.(60000)||window.LuminaGPS?.lastFix;if(Number.isFinite(+p?.lat)&&Number.isFinite(+p?.lng))return{lat:+p.lat,lng:+p.lng,accuracy:p.accuracy||null};if(window.LuminaGPS?.getPosition)return window.LuminaGPS.getPosition({maxAge:60000,timeout:7000});throw new Error('gps-unavailable')}
async function fetchMapbox(q,o,key,maxRadius){const u=new URL(MAPBOX_API);u.searchParams.set('q',q);u.searchParams.set('access_token',key);u.searchParams.set('language','el');u.searchParams.set('limit','10');u.searchParams.set('proximity',`${o.lng},${o.lat}`);u.searchParams.set('country','GR');u.searchParams.set('types','poi');const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(u,{cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{}if(!r.ok){const e=new Error(`HTTP ${r.status}`);e.status=r.status;throw e}return(d.features||[]).map(f=>{const p=f.properties||{},co=f.geometry?.coordinates||[],pt={lat:+co[1],lng:+co[0]};if(!Number.isFinite(pt.lat)||!Number.isFinite(pt.lng)||!p.name)return null;const dist=distance(o,pt);if(dist>maxRadius)return null;return{name:p.name,point:pt,distance:dist,area:p.full_address||p.place_formatted||p.address||'Κοντινή περιοχή',source:'Mapbox'}}).filter(Boolean)}finally{clearTimeout(t)}}
function overpassQuery(g,o,radius){const clauses=[];for(const [k,v] of g.osm)for(const kind of ['node','way','relation'])clauses.push(`${kind}(around:${radius},${o.lat},${o.lng})["${k}"="${v}"][name];`);return`[out:json][timeout:20];(${clauses.join('')});out center tags;`}
function osmPoint(e){if(Number.isFinite(e.lat)&&Number.isFinite(e.lon))return{lat:e.lat,lng:e.lon};if(Number.isFinite(e.center?.lat)&&Number.isFinite(e.center?.lon))return{lat:e.center.lat,lng:e.center.lon};return null}
async function fetchOverpass(g,o,radius){const q=overpassQuery(g,o,radius);let last;for(const ep of OVERPASS){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),22000);const r=await fetch(ep,{method:'POST',body:q,signal:c.signal,headers:{'Content-Type':'text/plain;charset=UTF-8'}});clearTimeout(t);if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();return(d.elements||[]).map(e=>{const p=osmPoint(e),t=e.tags||{},name=t['name:el']||t.name||t.brand||t.operator;if(!p||!name)return null;const dist=distance(o,p);if(dist>radius)return null;const area=t['addr:street']||t['addr:place']||t['addr:city']||t['addr:town']||t['addr:village']||'Κοντινή περιοχή';return{name,point:p,distance:dist,area,source:'OpenStreetMap'}}).filter(Boolean)}catch(e){last=e}}console.warn('[LUMINA Overpass]',last);return[]}
function merge(groups){const out=[];for(const x of groups.flat().filter(Boolean).sort((a,b)=>a.distance-b.distance)){const n=norm(x.name);const dup=out.find(y=>distance(x.point,y.point)<35||(distance(x.point,y.point)<160&&n&&norm(y.name)===n));if(dup){if(dup.source!==x.source&&!dup.source.includes(x.source))dup.source=`${dup.source} + ${x.source}`;continue}out.push(x)}return out.slice(0,120)}
function root(){if(!cats||!results)return;title.textContent='Σημεία ενδιαφέροντος';back.classList.add('hidden');results.innerHTML='';cats.innerHTML=Object.entries(GROUPS).map(([k,g])=>`<button type="button" class="poi-category" data-curated-group="${k}"><strong>${g.label}</strong><span>${g.subtitle}</span></button>`).join('')}
async function run(k){const g=GROUPS[k],key=token();if(!g||!results)return;title.textContent=g.label.replace(/^\S+\s/,'');back.classList.remove('hidden');cats.innerHTML='';results.innerHTML='<div class="poi-loading busy"><span class="poi-spinner"></span><strong>Mapbox + OpenStreetMap: βρίσκω όλα τα κοντινά σημεία…</strong></div>';try{const o=await gps();const mapboxPromise=key?Promise.all(g.queries.map(q=>fetchMapbox(q,o,key,g.maxRadius).catch(()=>[]))):Promise.resolve([]);let osm=[],radius=RADII[0];for(const r of RADII){if(r>g.maxRadius)break;radius=r;osm=await fetchOverpass(g,o,r);if(osm.length>=g.minUseful||r===g.maxRadius)break}const mapbox=await mapboxPromise;const all=merge([mapbox.flat(),osm]);if(!all.length){results.innerHTML=`<div class="poi-loading">Δεν βρέθηκαν σημεία για ${esc(g.label)} έως ${fd(g.maxRadius)}.</div>`;return}let displayRadius=radius;for(const r of RADII){if(r>g.maxRadius)break;const count=all.filter(x=>x.distance<=r).length;if(count>=g.minUseful||r===g.maxRadius){displayRadius=r;break}}const items=all.filter(x=>x.distance<=displayRadius);const providers=[...new Set(items.flatMap(x=>x.source.split(' + ')))].join(' + ');results.innerHTML=`<div class="poi-loading"><strong>${items.length} κοντινά σημεία</strong><br><small>${esc(providers)} · ${esc(g.label)} · έως ${fd(displayRadius)} · από το κοντινότερο · GPS${o.accuracy?` ±${Math.round(o.accuracy)}m`:''}</small></div>`+items.map((x,i)=>`<article class="poi-result"><div><strong>${i+1}. ${esc(x.name)}</strong><span>${fd(x.distance)} · ${esc(x.area)}</span></div><button type="button" class="poi-route" data-lat="${x.point.lat}" data-lng="${x.point.lng}" data-name="${esc(x.name)}">▶ Έναρξη</button></article>`).join('')}catch(e){results.innerHTML=`<div class="poi-loading error"><strong>Αναζήτηση POI: ${esc(e?.message||'σφάλμα')}</strong></div>`}}
function open(){drawer?.classList.remove('hidden');root()}
function close(){drawer?.classList.add('hidden')}
document.addEventListener('click',e=>{const openBtn=e.target.closest?.('#poiOpenBtn,#navPoiBtn'),closeBtn=e.target.closest?.('#poiCloseBtn'),backBtn=e.target.closest?.('#poiBackBtn'),g=e.target.closest?.('[data-curated-group]');if(openBtn){e.preventDefault();e.stopImmediatePropagation();open();return}if(closeBtn){e.preventDefault();e.stopImmediatePropagation();close();return}if(backBtn){e.preventDefault();e.stopImmediatePropagation();root();return}if(g){e.preventDefault();e.stopImmediatePropagation();run(g.dataset.curatedGroup);return}},true);
window.LuminaCuratedPOI={open,root,run,groups:GROUPS};
})();
