(()=>{
  const $=s=>document.querySelector(s);
  const CATEGORIES={
    stay:{label:'Διαμονή',items:[['hotel','🏨 Ξενοδοχεία','tourism','hotel'],['motel','🛏️ Μοτέλ','tourism','motel'],['guest_house','🏡 Ξενώνες','tourism','guest_house'],['camp_site','⛺ Camping','tourism','camp_site']]},
    food:{label:'Φαγητό & Ποτό',items:[['restaurant','🍽️ Εστιατόρια','amenity','restaurant'],['fast_food','🍔 Fast food / Σουβλάκι','amenity','fast_food'],['cafe','☕ Καφέ','amenity','cafe'],['bar','🍸 Bar','amenity','bar'],['ice_cream','🍦 Παγωτό','amenity','ice_cream']]},
    shopping:{label:'Αγορές',items:[['supermarket','🛒 Supermarket','shop','supermarket'],['convenience','🥤 Mini market','shop','convenience'],['bakery','🥖 Φούρνοι','shop','bakery'],['mall','🏬 Εμπορικά κέντρα','shop','mall']]},
    health:{label:'Υγεία',items:[['pharmacy','💊 Φαρμακεία','amenity','pharmacy'],['hospital','🏥 Νοσοκομεία','amenity','hospital'],['clinic','🩺 Κλινικές','amenity','clinic'],['dentist','🦷 Οδοντίατροι','amenity','dentist']]},
    mobility:{label:'Μετακίνηση',items:[['fuel','⛽ Βενζινάδικα','amenity','fuel'],['parking','🅿️ Parking','amenity','parking'],['charging','⚡ Φόρτιση EV','amenity','charging_station'],['taxi','🚕 Taxi','amenity','taxi'],['bus','🚌 Στάσεις λεωφορείου','highway','bus_stop']]},
    services:{label:'Υπηρεσίες',items:[['bank','🏦 Τράπεζες','amenity','bank'],['atm','💶 ATM','amenity','atm'],['police','👮 Αστυνομία','amenity','police'],['post','📮 Ταχυδρομεία','amenity','post_office']]},
    leisure:{label:'Αναψυχή',items:[['gym','🏋️ Γυμναστήρια','leisure','fitness_centre'],['beach','🏖️ Παραλίες','natural','beach'],['museum','🏛️ Μουσεία','tourism','museum'],['attraction','📸 Αξιοθέατα','tourism','attraction'],['playground','🛝 Παιδικές χαρές','leisure','playground']]}
  };
  const drawer=$('#poiDrawer'),cats=$('#poiCategories'),results=$('#poiResults'),title=$('#poiTitle'),back=$('#poiBackBtn');
  function open(){drawer.classList.remove('hidden');renderCategories()}
  function close(){drawer.classList.add('hidden')}
  function renderCategories(){title.textContent='Σημεία ενδιαφέροντος';back.classList.add('hidden');results.innerHTML='';cats.innerHTML=Object.entries(CATEGORIES).map(([k,v])=>`<button class="poi-category" data-poi-group="${k}"><strong>${v.label}</strong><span>${v.items.length} κατηγορίες</span></button>`).join('');}
  function renderGroup(key){const g=CATEGORIES[key];if(!g)return;title.textContent=g.label;back.classList.remove('hidden');cats.innerHTML=g.items.map(i=>`<button class="poi-item" data-poi-type="${i[0]}" data-k="${i[2]}" data-v="${i[3]}">${i[1]}</button>`).join('');results.innerHTML='';}
  function getPos(){return new Promise((res,rej)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,lng:p.coords.longitude}),rej,{enableHighAccuracy:true,maximumAge:5000,timeout:12000}):rej())}
  const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const rad=v=>v*Math.PI/180;function distance(a,b){const R=6371e3,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
  const fd=m=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`;
  async function search(k,v){results.innerHTML='<div class="poi-loading">Αναζήτηση κοντά σου…</div>';try{const c=await getPos(),q=`[out:json][timeout:18];(node(around:10000,${c.lat},${c.lng})[${k}=${v}];way(around:10000,${c.lat},${c.lng})[${k}=${v}];relation(around:10000,${c.lat},${c.lng})[${k}=${v}];);out center tags 40;`,r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q});if(!r.ok)throw 0;const j=await r.json(),arr=[];for(const x of j.elements){const p=x.lat?{lat:x.lat,lng:x.lon}:x.center?{lat:x.center.lat,lng:x.center.lon}:null;if(!p)continue;arr.push({p,d:distance(c,p),name:x.tags?.name||x.tags?.brand||'Χωρίς καταχωρημένο όνομα',address:[x.tags?.['addr:street'],x.tags?.['addr:housenumber']].filter(Boolean).join(' ')})}arr.sort((a,b)=>a.d-b.d);results.innerHTML=arr.length?arr.slice(0,20).map(x=>`<article class="poi-result"><div><strong>${esc(x.name)}</strong><span>${fd(x.d)}${x.address?' · '+esc(x.address):''}</span></div><button class="poi-route" data-lat="${x.p.lat}" data-lng="${x.p.lng}" data-name="${esc(x.name)}">Οδηγίες</button></article>`).join(''):'<div class="poi-loading">Δεν βρέθηκαν αποτελέσματα κοντά σου.</div>'}catch{results.innerHTML='<div class="poi-loading">Δεν ήταν δυνατή η αναζήτηση. Έλεγξε GPS και σύνδεση.</div>'}}
  $('#poiOpenBtn')?.addEventListener('click',open);$('#poiCloseBtn')?.addEventListener('click',close);back?.addEventListener('click',renderCategories);cats?.addEventListener('click',e=>{const g=e.target.closest('[data-poi-group]');if(g)return renderGroup(g.dataset.poiGroup);const i=e.target.closest('[data-k]');if(i)search(i.dataset.k,i.dataset.v)});results?.addEventListener('click',e=>{if(e.target.closest('.poi-route'))close()});

  // Destination autocomplete loader. Kept here so current deployed HTML picks it up immediately.
  if(!document.getElementById('lumina-autocomplete-css')){const l=document.createElement('link');l.id='lumina-autocomplete-css';l.rel='stylesheet';l.href='./address-autocomplete.css?v=16';document.head.appendChild(l)}
  if(!document.getElementById('lumina-autocomplete-js')){const s=document.createElement('script');s.id='lumina-autocomplete-js';s.src='./address-autocomplete.js?v=16';s.defer=true;document.body.appendChild(s)}
})();