import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, AlertTriangle, ChevronDown, Code2, FileWarning, FolderGit2, Loader2, Play, RefreshCw, ShieldCheck, TerminalSquare, XCircle } from 'lucide-react';
import { apiGet, apiPost } from '../lib/api';
import { EMPTY_DEVELOPER_OVERVIEW, formatDuration, mergeDeveloperEvent, normalizeDeveloperOverview, pollingFallbackForSse, relativeTime, STATUS_STYLE, statusLabel, subscribeDeveloperEvents, toSafeErrorMessage } from '../developer/model';

function StatusDot({ status }) { return <span className={`inline-block h-2.5 w-2.5 rounded-full ${STATUS_STYLE[status] || 'bg-white/30'}`} />; }
function PanelWarning({ message }) { return message ? <p role="status" className="mt-3 flex items-center gap-2 rounded-md border border-amber-400/20 bg-amber-400/5 px-3 py-2 text-xs text-amber-100/80"><AlertTriangle className="h-3.5 w-3.5" />{message}</p> : null; }

export default function DeveloperCenter() {
  const [overview, setOverview] = useState(EMPTY_DEVELOPER_OVERVIEW);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [logFilter, setLogFilter] = useState(''); const [details, setDetails] = useState(null);
  const [panelErrors, setPanelErrors] = useState({ overview: '', live: '', actions: '' });
  const loadingRef = useRef(false); const pollingRef = useRef(null);
  const load = useCallback(async ({ quiet = false } = {}) => {
    if (loadingRef.current) return;
    loadingRef.current = true; if (!quiet) setLoading(true);
    try {
      setOverview(normalizeDeveloperOverview(await apiGet('/developer/overview')));
      setPanelErrors((current) => ({ ...current, overview: '' }));
    } catch (error) {
      setPanelErrors((current) => ({ ...current, overview: toSafeErrorMessage(error, 'Developer Center data is unavailable. You can still use the available local actions.') }));
    } finally { loadingRef.current = false; if (!quiet) setLoading(false); }
  }, []);
  useEffect(() => {
    let active = true; const controller = new AbortController();
    const startPolling = () => {
      if (!pollingRef.current) pollingRef.current = setInterval(() => { if (active) load({ quiet: true }); }, 15000);
    };
    load();
    subscribeDeveloperEvents((event, payload) => { if (active) setOverview((current) => mergeDeveloperEvent(current, event, payload)); }, controller.signal)
      .catch((error) => { if (active && !controller.signal.aborted) { const fallback = pollingFallbackForSse(error); setPanelErrors((current) => ({ ...current, live: fallback.message })); startPolling(); } });
    return () => { active = false; controller.abort(); if (pollingRef.current) { clearInterval(pollingRef.current); pollingRef.current = null; } };
  }, [load]);
  const run = async (taskType) => {
    setBusy(taskType); setPanelErrors((current) => ({ ...current, actions: '' }));
    try { await apiPost('/developer/tasks', { task_type: taskType }); await load({ quiet: true }); }
    catch (error) { setPanelErrors((current) => ({ ...current, actions: toSafeErrorMessage(error, 'This local action could not be started.') })); }
    finally { setBusy(''); }
  };
  const data = normalizeDeveloperOverview(overview);
  const filteredLogs = useMemo(() => data.logs.filter((log) => !logFilter || log.severity === logFilter), [data.logs, logFilter]);
  const activeTasks = data.tasks.filter((task) => ['queued', 'running'].includes(task.status));
  return <main className="h-full w-full overflow-y-auto" data-testid="developer-center-page"><div className="mx-auto max-w-[1540px] p-6 sm:p-10"><header className="flex flex-col gap-4 border-b border-white/[0.07] pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] uppercase tracking-[0.28em] text-gold">Local Developer Center</p><h2 className="mt-2 font-display text-4xl text-white sm:text-5xl">System care, made simple.</h2><p className="mt-2 max-w-2xl text-sm text-white/50">This page monitors only local LUMINA activity on this computer. It does not monitor external AI task sessions.</p></div><button onClick={() => load()} className="rounded-md border border-white/10 px-3 py-2 text-xs text-white/70 hover:text-white"><RefreshCw className={`mr-2 inline h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />Refresh</button></header>
    <PanelWarning message={panelErrors.overview} />
    <section className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.health.checks.map((check, index) => <button key={`${check.name}-${index}`} onClick={() => setDetails(check)} className="lumina-glass rounded-xl p-5 text-left hover:border-gold/35"><div className="flex items-center justify-between"><span className="text-sm text-white">{check.name}</span><StatusDot status={check.status} /></div><p className="mt-3 text-xs text-white/45">{statusLabel(check.status)}</p><p className="mt-1 text-[11px] text-white/30">Details available</p></button>)}{!data.health.checks.length && <div className="lumina-glass rounded-xl p-5 text-xs text-white/45">Local health details are unavailable.</div>}</section>
    <section className="mt-8 grid gap-6 xl:grid-cols-3"><div className="lumina-glass rounded-xl p-6 xl:col-span-2"><div className="flex items-center gap-2"><Play className="h-4 w-4 text-gold" /><h3 className="font-display text-3xl text-white">Safe local actions</h3></div><p className="mt-1 text-xs text-white/45">Only approved local checks can run here. Commands cannot be entered manually.</p><PanelWarning message={panelErrors.actions} /><div className="mt-5 grid gap-2 sm:grid-cols-2">{['backend_tests', 'frontend_tests', 'frontend_build', 'python_compile', 'backend_health', 'frontend_health', 'repository_status'].map((type) => <button key={type} onClick={() => run(type)} disabled={!!busy} data-testid={`developer-action-${type}`} className="flex items-center justify-between rounded-lg bg-white/[0.035] px-4 py-3 text-left text-xs text-white/75 hover:bg-white/[0.07] disabled:opacity-40"><span>{({ backend_tests: 'Run backend tests', frontend_tests: 'Run frontend tests', frontend_build: 'Build frontend', python_compile: 'Check Python code', backend_health: 'Check backend health', frontend_health: 'Check frontend health', repository_status: 'Refresh repository status' })[type]}</span>{busy === type ? <Loader2 className="h-4 w-4 animate-spin text-gold" /> : <Play className="h-3.5 w-3.5 text-gold" />}</button>)}</div></div><div className="lumina-glass rounded-xl p-6"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-gold" /><h3 className="font-display text-3xl text-white">Now running</h3></div><PanelWarning message={panelErrors.live} /><div className="mt-5 space-y-3">{activeTasks.map((task) => <div key={task.id} className="rounded-lg bg-white/[0.03] p-3"><div className="flex items-center justify-between"><span className="text-xs text-white/75">{task.label}</span><StatusDot status={task.status} /></div><p className="mt-1 text-[11px] text-white/40">{task.status === 'running' ? 'Working locally' : 'Waiting safely in line'}</p></div>)}{!activeTasks.length && <p className="rounded-lg border border-dashed border-white/10 p-4 text-center text-xs text-white/45">No local development task is running.</p>}</div></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="lumina-glass rounded-xl p-6"><div className="flex items-center gap-2"><TerminalSquare className="h-4 w-4 text-gold" /><h3 className="font-display text-3xl text-white">Recent local tasks</h3></div><div className="mt-5 space-y-2">{data.tasks.slice(0, 6).map((task) => <button key={task.id} onClick={() => setDetails(task)} className="flex w-full items-center justify-between rounded-lg bg-white/[0.025] px-3 py-3 text-left hover:bg-white/[0.05]"><span><span className="flex items-center gap-2 text-xs text-white/75"><StatusDot status={task.status} />{task.label}</span><span className="mt-1 block text-[11px] text-white/35">{relativeTime(task.finished_at || task.started_at || task.created_at)} · {formatDuration(task.duration_seconds)}</span></span><ChevronDown className="h-3.5 w-3.5 text-white/30" /></button>)}</div></div><div className="lumina-glass rounded-xl p-6"><div className="flex items-center gap-2"><FolderGit2 className="h-4 w-4 text-gold" /><h3 className="font-display text-3xl text-white">Repository</h3></div><PanelWarning message={data.panel_errors.repository} /><p className="mt-3 text-xs text-white/55">Branch: <span className="text-white">{data.repository.branch}</span> · {data.repository.clean ? 'No local changes' : `${data.repository.uncommitted_count} local changes`}</p><div className="mt-4 max-h-36 space-y-2 overflow-y-auto">{data.repository.changed_files.slice(0, 8).map((item, index) => <div key={`${item.status}-${item.path}-${index}`} className="flex gap-2 text-[11px]"><span className="w-6 text-gold">{item.status}</span><span className="truncate text-white/55">{item.path}</span></div>)}{!data.repository.changed_files.length && <p className="text-xs text-white/40">No changed files.</p>}</div><p className="mt-4 text-[11px] text-white/35">{data.repository.last_commit}</p></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="lumina-glass rounded-xl p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><FileWarning className="h-4 w-4 text-gold" /><h3 className="font-display text-3xl text-white">Local logs</h3></div><select value={logFilter} onChange={(event) => setLogFilter(event.target.value)} className="bg-black/40 text-xs text-white/65"><option value="">All</option><option value="info">Information</option><option value="warning">Warnings</option><option value="error">Errors</option></select></div><div className="mt-5 max-h-64 space-y-2 overflow-y-auto">{filteredLogs.map((log, index) => <div key={`${log.timestamp}-${index}`} className="rounded-md bg-white/[0.025] px-3 py-2"><div className="flex justify-between text-[10px] text-white/35"><span>{log.source}</span><span>{relativeTime(log.timestamp)}</span></div><p className="mt-1 text-xs text-white/65">{log.message}</p></div>)}{!filteredLogs.length && <p className="text-xs text-white/40">No retained local logs.</p>}</div></div><div className="lumina-glass rounded-xl p-6"><div className="flex items-center gap-2"><Code2 className="h-4 w-4 text-gold" /><h3 className="font-display text-3xl text-white">Application jobs</h3></div><PanelWarning message={data.panel_errors.media_jobs} /><div className="mt-5 space-y-2">{data.media_jobs.map((job) => <div key={job.id} className="rounded-md bg-white/[0.025] px-3 py-2"><div className="flex justify-between gap-3 text-xs"><span className="truncate text-white/70">{job.title}</span><span className="capitalize text-gold">{job.status}</span></div></div>)}{!data.media_jobs.length && <p className="text-xs text-white/40">No media jobs are active.</p>}</div></div></section>
    <p className="mt-6 flex items-center gap-2 text-[11px] text-white/35"><ShieldCheck className="h-3.5 w-3.5 text-emerald-400" />Last local refresh: {data.refreshed_at ? new Date(data.refreshed_at).toLocaleTimeString() : 'Waiting for data'}</p>
    {details && <div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/70 p-5" onClick={() => setDetails(null)}><div className="lumina-glass max-h-[80vh] w-full max-w-xl overflow-y-auto rounded-xl p-6" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><h3 className="font-display text-3xl text-white">Details</h3><button onClick={() => setDetails(null)}><XCircle className="h-5 w-5 text-white/45" /></button></div><pre className="mt-5 whitespace-pre-wrap break-words rounded-lg bg-black/40 p-4 text-xs leading-relaxed text-white/65">{JSON.stringify(details, null, 2)}</pre></div></div>}
  </div></main>;
}
