import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { apiDelete, apiGet, apiPatch, apiPost } from '../lib/api';

const message = (error, fallback) => typeof error?.message === 'string' ? error.message : fallback;
const Empty = ({ children }) => <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-white/45">{children}</div>;

function MediaLibrary() {
  const [items, setItems] = useState([]); const [q, setQ] = useState(''); const [type, setType] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [grid, setGrid] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const data = await apiGet('/media-library', { params: { q, media_type: type } }); setItems(data.items || []); setError(''); } catch (e) { setError(message(e, 'Media Library is unavailable.')); } finally { setLoading(false); } }, [q, type]); useEffect(() => { const timer = setTimeout(load, 200); return () => clearTimeout(timer); }, [load]);
  const update = async (item, body) => { try { const next = await apiPatch(`/media-library/${item.id}`, body); setItems((rows) => rows.map((row) => row.id === item.id ? next : row)); } catch (e) { setError(message(e, 'Media could not be updated.')); } };
  return <main className="h-full overflow-y-auto"><div className="mx-auto max-w-[1500px] p-6 sm:p-10"><h2 className="font-display text-4xl text-white">Media Library</h2><p className="mt-2 text-sm text-white/50">Every private image, video, audio asset, and export in one place.</p><div className="mt-6 flex flex-wrap gap-2"><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search media or tags" className="min-w-56 flex-1 rounded bg-white/5 px-3 py-2 text-sm text-white" /><select value={type} onChange={(e) => setType(e.target.value)} className="rounded bg-white/5 px-3 text-sm text-white"><option value="">All types</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option></select><button onClick={() => setGrid(!grid)} className="rounded border border-white/10 px-3 text-xs text-white/65">{grid ? 'List' : 'Grid'}</button></div>{error && <p role="alert" className="mt-4 text-amber-200">{error}</p>}<div className={`mt-6 gap-3 ${grid ? 'grid sm:grid-cols-2 xl:grid-cols-4' : 'space-y-2'}`}>{items.map((item) => <div key={item.id} className="lumina-glass rounded-xl p-4"><div className="aspect-video rounded bg-white/[.04]" /><p className="mt-3 truncate text-sm text-white">{item.edit_note || item.mime_type}</p><p className="mt-1 text-xs text-white/40">{item.source_module || 'workspace'} · {item.provider || 'Local'}</p><div className="mt-3 flex gap-3 text-xs"><button onClick={() => update(item, { favorite: !item.favorite })} className="text-gold">{item.favorite ? '★ Favorite' : '☆ Favorite'}</button><button onClick={() => update(item, { tags: [...(item.tags || []), 'review'] })} className="text-white/55">Tag</button></div></div>)}{!loading && !items.length && <Empty>No matching private media yet.</Empty>}{loading && <Empty>Loading media…</Empty>}</div></div></main>;
}

function JobsCenter() { const [jobs, setJobs] = useState([]); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const load = useCallback(async () => { try { setJobs((await apiGet('/workspace/jobs', { params: { status } })).jobs || []); } catch (e) { setError(message(e, 'Jobs Center is unavailable.')); } }, [status]); useEffect(() => { load(); }, [load]); return <main className="h-full overflow-y-auto"><div className="mx-auto max-w-[1500px] p-6 sm:p-10"><h2 className="font-display text-4xl text-white">Jobs Center</h2><select value={status} onChange={(e) => setStatus(e.target.value)} className="mt-6 rounded bg-white/5 p-2 text-white"><option value="">All statuses</option>{['queued','preparing','processing','rendering','completed','failed','cancelled'].map((x) => <option key={x}>{x}</option>)}</select>{error && <p className="mt-4 text-amber-200">{error}</p>}<div className="mt-5 space-y-2">{jobs.map((job) => <div key={`${job.module}-${job.id}`} className="lumina-glass flex items-center justify-between rounded-xl p-4"><span className="text-sm text-white">{job.title || job.prompt || job.text || 'Workspace job'}</span><span className="text-xs text-gold">{job.module} · {job.status}</span></div>)}{!jobs.length && <Empty>No jobs match this filter.</Empty>}</div></div></main>; }

function Notifications() { const [rows, setRows] = useState([]); const [error, setError] = useState(''); const load = useCallback(async () => { try { setRows(await apiGet('/notifications')); } catch (e) { setError(message(e, 'Notifications are unavailable.')); } }, []); useEffect(() => { load(); }, [load]); const markAll = async () => { await apiPost('/notifications/mark-all-read', {}); load(); }; return <main className="h-full overflow-y-auto"><div className="mx-auto max-w-4xl p-6 sm:p-10"><div className="flex justify-between"><h2 className="font-display text-4xl text-white">Notifications</h2><button onClick={markAll} className="text-xs text-gold">Mark all read</button></div>{error && <p className="mt-4 text-amber-200">{error}</p>}<div className="mt-6 space-y-2">{rows.map((row) => <div key={row.id} className={`lumina-glass flex justify-between rounded-xl p-4 ${row.read ? 'opacity-60' : ''}`}><span><b className="text-sm text-white">{row.title}</b><span className="ml-2 text-xs text-white/45">{row.message}</span></span><span className="flex gap-3 text-xs"><button onClick={() => apiPatch(`/notifications/${row.id}`, { read: true }).then(load)}>Read</button><button onClick={() => apiDelete(`/notifications/${row.id}`).then(load)}>Dismiss</button></span></div>)}{!rows.length && <Empty>No notifications right now.</Empty>}</div></div></main>; }
export default function PlatformHub({ mode }) { return mode === 'media' ? <MediaLibrary /> : mode === 'jobs' ? <JobsCenter /> : <Notifications />; }
