import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { apiGet, apiPatch } from '../lib/api';

export default function ProjectDetail() {
  const { projectId } = useParams(); const [project, setProject] = useState(null); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setProject(await apiGet(`/projects/${projectId}`)); } catch { setError('Project not found or unavailable.'); } }, [projectId]); useEffect(() => { load(); }, [load]);
  const saveNotes = async () => { try { setProject(await apiPatch(`/projects/${projectId}`, { description: project.description, notes: project.notes, tags: project.tags })); } catch { setError('Changes could not be saved.'); } };
  if (error) return <main className="p-10 text-amber-200">{error}</main>; if (!project) return <main className="p-10 text-white/45">Loading project…</main>;
  return <main className="h-full overflow-y-auto"><div className="mx-auto max-w-5xl p-6 sm:p-10"><p className="text-[11px] uppercase tracking-[.28em] text-gold">Project workspace</p><h2 className="mt-2 font-display text-4xl text-white">{project.name}</h2><div className="mt-7 grid gap-5 lg:grid-cols-2"><div className="lumina-glass rounded-xl p-5"><label className="text-xs text-white/45">Description<textarea value={project.description} onChange={(e) => setProject({ ...project, description: e.target.value })} className="mt-2 min-h-24 w-full rounded bg-black/30 p-3 text-white" /></label><label className="mt-4 block text-xs text-white/45">Notes<textarea value={project.notes} onChange={(e) => setProject({ ...project, notes: e.target.value })} className="mt-2 min-h-40 w-full rounded bg-black/30 p-3 text-white" /></label><button onClick={saveNotes} className="mt-4 rounded bg-gold px-4 py-2 text-sm text-black">Save project</button></div><div className="lumina-glass rounded-xl p-5"><h3 className="text-white">Linked work</h3><p className="mt-4 text-sm text-white/55">{project.media_ids.length} media · {project.job_ids.length} jobs · {project.identity_pack_ids.length} identity packs · {project.export_media_ids.length} exports</p><h3 className="mt-7 text-white">Recent activity</h3><div className="mt-3 space-y-2">{project.activity.map((item, index) => <p key={index} className="text-xs text-white/45">{item.message}</p>)}</div></div></div></div></main>;
}
