import { useCallback, useEffect, useRef, useState } from 'react';
import { Clipboard, Download, History, Loader2, PauseCircle, Play, RefreshCcw, Upload, UserRoundCog, Wand2, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiPost, uploadFormData } from '../lib/api';
import { ACTIVE_INSTALL_STATUSES, ACTIVE_TALKING_PORTRAIT_STATUSES, buildTalkingPortraitForm, installDiagnosticsText, installElapsedLabel, normalizeInstallJob, jobEtaLabel, providerNeedsInstall } from '../talkingPortrait/model';

const date = (value) => value ? new Date(value).toLocaleString() : '—';

export default function TalkingPortraitStudio() {
  const [photo, setPhoto] = useState(null);
  const [audio, setAudio] = useState(null);
  const [identityLock, setIdentityLock] = useState(true);
  const [naturalBlinking, setNaturalBlinking] = useState(true);
  const [headMotion, setHeadMotion] = useState(0.35);
  const [expressionIntensity, setExpressionIntensity] = useState(0.55);
  const [title, setTitle] = useState('Talking portrait');
  const [providerInfo, setProviderInfo] = useState(null);
  const [install, setInstall] = useState(null);
  const [job, setJob] = useState(null);
  const [jobs, setJobs] = useState([]);
  const [preview, setPreview] = useState('');
  const [loading, setLoading] = useState(true);
  const [now, setNow] = useState(Date.now());
  const previewRef = useRef('');
  const releasePreview = useCallback(() => { if (previewRef.current) URL.revokeObjectURL(previewRef.current); previewRef.current = ''; setPreview(''); }, []);
  const loadProviders = useCallback(() => apiGet('/talking-portrait/providers').then(setProviderInfo).catch((error) => toast.error(error.message)), []);
  const loadJobs = useCallback(async () => { setLoading(true); try { setJobs(await apiGet('/talking-portrait/jobs')); } catch (error) { toast.error(error.message); } finally { setLoading(false); } }, []);
  const loadPreview = useCallback(async (item) => { if (!item?.output_media_id) return; releasePreview(); const blob = await apiGet(`/talking-portrait/results/${item.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(blob); previewRef.current = url; setPreview(url); }, [releasePreview]);
  useEffect(() => { loadProviders(); loadJobs(); const stored = localStorage.getItem('lumina_liveportrait_install_job_id'); if (stored) apiGet(`/talking-portrait/install/${stored}`).then((job) => setInstall(normalizeInstallJob(job))).catch(() => localStorage.removeItem('lumina_liveportrait_install_job_id')); return releasePreview; }, [loadJobs, loadProviders, releasePreview]);
  useEffect(() => { if (!job || !ACTIVE_TALKING_PORTRAIT_STATUSES.has(job.status)) return; const timer = setTimeout(async () => { const next = await apiGet(`/talking-portrait/jobs/${job.id}`); setJob(next); if (next.status === 'completed') { await loadPreview(next); loadJobs(); } }, 1000); return () => clearTimeout(timer); }, [job, loadJobs, loadPreview]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { if (!install || !ACTIVE_INSTALL_STATUSES.has(install.status)) return; const timer = setTimeout(async () => { const next = normalizeInstallJob(await apiGet(`/talking-portrait/install/${install.install_job_id || install.id}`)); setInstall(next); localStorage.setItem('lumina_liveportrait_install_job_id', next.install_job_id); if (next.status === 'completed') { loadProviders(); } }, 1200); return () => clearTimeout(timer); }, [install, loadProviders]);

  async function installLivePortrait() { try { const created = normalizeInstallJob(await apiPost('/talking-portrait/install', { provider: 'liveportrait' }, { timeout: 5000 })); setInstall(created); localStorage.setItem('lumina_liveportrait_install_job_id', created.install_job_id); toast.success('LivePortrait installer started.'); } catch (error) { toast.error(error.message); } }
  async function cancelInstall() { if (!install) return; try { setInstall(normalizeInstallJob(await apiPost(`/talking-portrait/install/${install.install_job_id || install.id}/cancel`))); } catch (error) { toast.error(error.message); } }
  async function retryInstall() { if (!install) return installLivePortrait(); try { const next = normalizeInstallJob(await apiPost(`/talking-portrait/install/${install.install_job_id || install.id}/retry`, null, { timeout: 5000 })); setInstall(next); localStorage.setItem('lumina_liveportrait_install_job_id', next.install_job_id); } catch (error) { toast.error(error.message); } }
  async function copyDiagnostics() { if (!install) return; await navigator.clipboard.writeText(installDiagnosticsText(install)); toast.success('Diagnostics copied.'); }
  async function generate(event) {
    event.preventDefault();
    if (!photo) return toast.error('Upload one reference photo.');
    if (!audio) return toast.error('Upload one audio file.');
    try { const created = await uploadFormData('/talking-portrait/generate', buildTalkingPortraitForm({ photo, audio, identityLock, naturalBlinking, headMotion, expressionIntensity, title, provider: providerInfo?.active || 'liveportrait' }), { timeout: 60000 }); setJob(created); toast.success('Talking portrait job queued.'); loadJobs(); } catch (error) { toast.error(error.message); }
  }
  async function action(type, item = job) { try { const next = await apiPost(`/talking-portrait/jobs/${item.id}/${type}`); setJob(next); loadJobs(); } catch (error) { toast.error(error.message); } }
  async function open(item) { setJob(item); if (item.status === 'completed') await loadPreview(item); }
  async function download(item = job) { const blob = await apiGet(`/talking-portrait/results/${item.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${item.title || 'lumina-talking-portrait'}.mp4`; a.click(); URL.revokeObjectURL(url); }
  const needsInstall = providerNeedsInstall(providerInfo);
  const activeProvider = providerInfo?.providers?.find((item) => item.name === providerInfo.active) || providerInfo?.providers?.[0];
  const computeLabel = activeProvider?.diagnostics?.gpu ? 'GPU' : 'CPU';
  const lipSyncEngine = activeProvider?.capabilities?.lip_sync_engine || activeProvider?.diagnostics?.lip_sync_engine;

  return <div className="h-full overflow-y-auto bg-ink-950" data-testid="talking-portrait-page"><div className="max-w-[1500px] mx-auto p-6 lg:p-10 space-y-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-gold text-xs tracking-[.25em] uppercase flex gap-2 items-center"><UserRoundCog className="w-4" />LUMINA Talking Portrait Studio</p><h1 className="font-display text-4xl text-white mt-2">Talking Portrait</h1><p className="text-white/45 mt-2">Generate an MP4 talking portrait from one private reference photo and one audio file using local LivePortrait motion plus real audio-driven lip sync.</p></div><span className="text-xs text-gold border border-gold/30 bg-gold/10 rounded-full px-3 py-1">LivePortrait · {lipSyncEngine || 'lip-sync engine required'} · {computeLabel}</span></header>
    {needsInstall && <InstallPanel install={install} now={now} onInstall={installLivePortrait} onCancel={cancelInstall} onRetry={retryInstall} onCopy={copyDiagnostics} />}
    <div className="grid xl:grid-cols-[minmax(0,.9fr)_minmax(430px,1fr)] gap-6"><form onSubmit={generate} className="lumina-glass rounded-xl p-5 space-y-5"><div className="grid sm:grid-cols-2 gap-4"><UploadBox label="Reference photo" file={photo} accept="image/png,image/jpeg,image/webp" onChange={setPhoto} /><UploadBox label="Audio file" file={audio} accept="audio/wav,audio/x-wav,audio/mpeg,audio/mp3,audio/webm,audio/ogg" onChange={setAudio} /></div><label className="block text-xs text-white/60">Title<input value={title} onChange={(event) => setTitle(event.target.value)} className="mt-2 w-full rounded bg-black/40 border border-white/10 p-3 text-sm text-white" /></label><div className="grid sm:grid-cols-2 gap-3"><Switch label="Identity Lock" value={identityLock} onChange={setIdentityLock} /><Switch label="Natural blinking" value={naturalBlinking} onChange={setNaturalBlinking} /></div><Slider label="Head motion" value={headMotion} onChange={setHeadMotion} /><Slider label="Expression intensity" value={expressionIntensity} onChange={setExpressionIntensity} /><div className="flex gap-2"><button className="bg-gold text-black rounded py-2.5 px-4 font-medium text-sm flex justify-center gap-2 disabled:opacity-50"><Wand2 className="w-4" />Generate</button>{job && ACTIVE_TALKING_PORTRAIT_STATUSES.has(job.status) && <button type="button" onClick={() => action('cancel')} className="rounded border border-red-400/30 px-4 text-red-200 flex gap-2 items-center"><PauseCircle className="w-4" />Cancel</button>}</div></form>
      <section className="lumina-glass rounded-xl p-5 min-h-[500px]"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-white/40">Preview</p><h2 className="font-display text-2xl text-white">{job?.title || 'Ready for portrait generation'}</h2></div>{job?.status === 'completed' && <button onClick={() => download()} className="text-gold"><Download /></button>}</div><div className="mt-5 min-h-[360px] bg-black/50 rounded flex items-center justify-center overflow-hidden">{job && ACTIVE_TALKING_PORTRAIT_STATUSES.has(job.status) && <div className="w-2/3 text-center"><Loader2 className="animate-spin text-gold mx-auto mb-3" /><p className="text-sm text-white capitalize">{job.status}</p><div className="h-2 bg-white/10 rounded mt-4"><div className="h-full bg-gold rounded" style={{ width: `${job.progress || 0}%` }} /></div><p className="text-xs text-white/40 mt-2">{job.progress || 0}% · {jobEtaLabel(job)}</p><p className="text-xs text-white/35 mt-2">{job.metadata?.stage || job.metadata?.install_stage || ''}</p><ol className="mt-4 text-left text-xs text-white/35 space-y-1"><ProgressStep done={(job.progress || 0) >= 38} label="Validate full uploaded audio duration" /><ProgressStep done={(job.progress || 0) >= 45} label="Create natural LivePortrait base motion" /><ProgressStep done={(job.progress || 0) >= 72} label="Run MuseTalk/Wav2Lip audio-driven lip sync" /><ProgressStep done={(job.progress || 0) >= 88} label="Merge complete original audio and validate A/V sync" /></ol></div>}{job?.status === 'completed' && preview && <video src={preview} controls autoPlay className="max-h-[460px] max-w-full" />}{['failed', 'cancelled'].includes(job?.status) && <div className="text-left max-w-full p-4"><p className="text-red-200 text-sm whitespace-pre-wrap">{job.error || `Job ${job.status}`}</p>{job.metadata?.error_details && <pre className="mt-3 max-h-56 overflow-auto rounded bg-black/60 p-3 text-xs text-red-100/80 whitespace-pre-wrap">{JSON.stringify(job.metadata.error_details, null, 2)}</pre>}<button onClick={() => action('retry')} className="mt-3 text-gold text-sm flex items-center gap-2 mx-auto"><RefreshCcw className="w-4" />Retry</button></div>}{!job && <div className="text-center text-white/35"><Play className="mx-auto mb-3" /><p>Upload a portrait and audio to generate a private MP4.</p><p className="mt-2 text-xs">Requires local MuseTalk (preferred) or Wav2Lip for real speech lip sync.</p></div>}</div>{job && <p className="text-xs text-white/40 mt-3">{job.provider} · Identity {job.identity_lock ? 'locked' : 'adaptive'} · Motion {job.head_motion} · Expression {job.expression_intensity} · {date(job.created_at)}</p>}</section></div>
    <section className="lumina-glass rounded-xl p-5"><h2 className="font-display text-2xl text-white flex gap-2 items-center"><History className="w-5 text-gold" />History</h2>{loading ? <Loader2 className="animate-spin text-gold mt-6" /> : <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3 mt-4">{jobs.map((item) => <article key={item.id} className="border border-white/10 bg-white/[.025] rounded p-4"><button onClick={() => open(item)} className="text-left text-white text-sm">{item.title}</button><p className="text-xs text-white/40 mt-1 capitalize">{item.status} · {item.progress}% · {date(item.created_at)}</p><div className="flex gap-3 mt-3 text-xs">{item.status === 'completed' && <button onClick={() => download(item)} className="text-gold">Download MP4</button>}{['failed', 'cancelled'].includes(item.status) && <button onClick={() => action('retry', item)} className="text-gold">Retry</button>}</div></article>)}</div>}</section>
  </div></div>;
}

function UploadBox({ label, file, accept, onChange }) { return <label className="block border border-dashed border-white/15 hover:border-gold/50 rounded-lg p-5 cursor-pointer text-center"><Upload className="w-5 text-gold mx-auto mb-2" /><span className="text-sm text-white/75">{label}</span><p className="text-xs text-white/35 mt-1 truncate">{file ? file.name : 'Private local upload'}</p><input className="sr-only" type="file" accept={accept} onChange={(event) => onChange(event.target.files?.[0] || null)} /></label>; }
function Switch({ label, value, onChange }) { return <button type="button" onClick={() => onChange(!value)} className={`rounded p-3 text-left border ${value ? 'border-gold/40 bg-gold/10 text-gold' : 'border-white/10 bg-black/30 text-white/55'}`}><div className="text-sm">{label}</div><div className="text-xs mt-1">{value ? 'Enabled' : 'Disabled'}</div></button>; }
function Slider({ label, value, onChange }) { return <label className="block text-xs text-white/60">{label}<div className="flex items-center gap-3 mt-2"><input type="range" min="0" max="1" step="0.01" value={value} onChange={(event) => onChange(Number(event.target.value))} className="w-full" /><span className="text-gold tabular-nums">{Math.round(value * 100)}%</span></div></label>; }
function ProgressStep({ done, label }) { return <li className={done ? 'text-gold' : 'text-white/35'}>{done ? '✓' : '•'} {label}</li>; }

function InstallPanel({ install, now, onInstall, onCancel, onRetry, onCopy }) {
  const active = install && ACTIVE_INSTALL_STATUSES.has(install.status);
  const failed = install?.status === 'failed';
  return <section className="rounded-xl border border-gold/30 bg-gold/10 p-4 space-y-4" data-testid="liveportrait-install-panel"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-white font-medium">LivePortrait is not installed</h2><p className="text-sm text-white/55 mt-1">Installer runs in the background, restores after refresh, validates checkpoints, torch, FFmpeg, GPU/CPU runtime, and smoke test.</p>{install?.metadata?.compute_mode === 'cpu' || install?.metadata?.cpu_fallback ? <p className="text-xs text-amber-200 mt-2">CPU fallback enabled. Generation will be slower.</p> : null}</div><div className="flex flex-wrap gap-2"><button onClick={onInstall} className="bg-gold text-black rounded px-4 py-2 font-medium disabled:opacity-50" disabled={active}>{active ? 'Installing…' : 'Install LivePortrait'}</button>{active && <button onClick={onCancel} className="rounded border border-red-400/30 px-3 py-2 text-red-200 flex gap-2 items-center"><XCircle className="w-4" />Cancel</button>}{failed && <button onClick={onRetry} className="rounded border border-gold/40 px-3 py-2 text-gold flex gap-2 items-center"><RefreshCcw className="w-4" />Retry</button>}{install && <button onClick={onCopy} className="rounded border border-white/15 px-3 py-2 text-white/70 flex gap-2 items-center"><Clipboard className="w-4" />Copy diagnostics</button>}</div></div>{install && <><div><div className="flex justify-between text-xs text-white/50 mb-1"><span>{install.stage || 'preflight'} · {install.status}</span><span>{install.progress || 0}% · elapsed {installElapsedLabel(install, now)}</span></div><div className="h-2 bg-black/40 rounded"><div className="h-full bg-gold rounded" style={{ width: `${install.progress || 0}%` }} /></div><p className="text-sm text-white/70 mt-2">{install.current_message || install.step}</p>{install.full_user_safe_error || install.error ? <p className="text-sm text-red-200 mt-2">{install.full_user_safe_error || install.error}</p> : null}</div><div className="rounded bg-black/40 border border-white/10 p-3"><p className="text-xs uppercase tracking-wider text-white/35 mb-2">Recent logs</p><pre className="text-[11px] text-white/55 whitespace-pre-wrap max-h-36 overflow-auto">{(install.recent_log_lines || install.log || []).slice(-12).join('\n') || 'Waiting for installer logs…'}</pre></div><details className="rounded border border-white/10 bg-black/20 p-3"><summary className="text-xs text-gold cursor-pointer">Technical details</summary><pre className="text-[11px] text-white/55 whitespace-pre-wrap mt-2 max-h-56 overflow-auto">{installDiagnosticsText(install)}</pre></details></>}</section>;
}
