import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, Copy, Download, Film, Grid2X2, Heart, List, Loader2, Pencil, Play, Plus, Search, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { apiDelete, apiGet, apiPatch, apiPost, uploadFormData } from '../lib/api';

export const MODES = [
  ['text-to-video', 'Text to Video'], ['image-to-video', 'Image to Video'], ['multi-image', 'Multiple Images'],
  ['variation', 'Variation'], ['extend', 'Extension'], ['interpolation', 'Interpolation'],
];
const ACTIVE = new Set(['queued', 'preparing', 'uploading', 'processing', 'rendering']);
const label = (value) => String(value || '').replaceAll('-', ' ');
const date = (value) => value ? new Date(value).toLocaleString() : '—';

export default function VideoStudio() {
  const [mode, setMode] = useState('image-to-video');
  const [files, setFiles] = useState([]);
  const [prompt, setPrompt] = useState(''); const [negative, setNegative] = useState('');
  const [duration, setDuration] = useState(5); const [aspect, setAspect] = useState('16:9');
  const [resolution, setResolution] = useState('720p'); const [fps, setFps] = useState(24);
  const [quality, setQuality] = useState('standard'); const [camera, setCamera] = useState('auto');
  const [style, setStyle] = useState('cinematic'); const [seed, setSeed] = useState(''); const [priority, setPriority] = useState(0);
  const [advanced, setAdvanced] = useState(false); const [job, setJob] = useState(null); const [jobs, setJobs] = useState([]);
  const [filters, setFilters] = useState({ search: '', status: '', favorite: false, sort: 'recent' });
  const [view, setView] = useState('grid'); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState(null);
  const [preview, setPreview] = useState(''); const previewRef = useRef('');
  const [providerInfo, setProviderInfo] = useState(null); const [facets, setFacets] = useState({ folders: [], collections: [] });
  const [libraryError, setLibraryError] = useState(''); const [providerError, setProviderError] = useState('');
  const sourceRequired = mode !== 'text-to-video';

  const releasePreview = useCallback(() => { if (previewRef.current) URL.revokeObjectURL(previewRef.current); previewRef.current = ''; setPreview(''); }, []);
  const loadJobs = useCallback(async () => {
    setLoading(true); setLibraryError(''); try { setJobs(await apiGet('/video/jobs', { params: filters })); } catch (e) { setLibraryError(e.message || 'The video library is temporarily unavailable.'); } finally { setLoading(false); }
  }, [filters]);
  const loadPreview = useCallback(async (item) => { if (!item?.output_media_id) return; releasePreview(); try { const blob = await apiGet(`/video/results/${item.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(blob); previewRef.current = url; setPreview(url); } catch (e) { toast.error(e.message); } }, [releasePreview]);
  useEffect(() => { loadJobs(); return releasePreview; }, [loadJobs, releasePreview]);
  useEffect(() => { apiGet('/video/providers').then((data) => setProviderInfo(data)).catch(() => setProviderError('Provider details are unavailable. Generation will use the server default.')); apiGet('/video/library/facets').then(setFacets).catch(() => {}); }, []);
  useEffect(() => { if (!job || !ACTIVE.has(job.status)) return; const timer = setTimeout(async () => { try { const next = await apiGet(`/video/jobs/${job.id}`); setJob(next); if (next.status === 'completed') { await loadPreview(next); loadJobs(); } } catch (e) { toast.error(e.message); } }, 900); return () => clearTimeout(timer); }, [job, loadJobs, loadPreview]);
  function choose(input) { const maximum = capabilities?.max_image_inputs || (mode === 'multi-image' || mode === 'interpolation' ? 8 : 1); const next = [...input].filter((f) => ['image/png','image/jpeg','image/webp'].includes(f.type)).slice(0, maximum); if (!next.length) return toast.error('Use PNG, JPEG, or WebP images.'); setFiles(next); }
  async function generate(e) { e.preventDefault(); const capability = capabilities; if (capability && (!capability.modes.includes(mode) || !capability.durations.includes(duration) || !capability.resolutions.includes(resolution) || !capability.aspect_ratios.includes(aspect))) return toast.error('The active video engine does not support one or more selected settings.'); if (sourceRequired && !files.length) return toast.error('Add a source image.'); if (!prompt.trim()) return toast.error('Describe the video you want.'); const data = new FormData(); files.forEach((file) => data.append('files', file)); Object.entries({ mode, prompt, negative_prompt: negative, duration_seconds: duration, aspect_ratio: aspect, resolution, fps, quality, camera_motion: camera, style, priority, seed: seed || '' }).forEach(([k,v]) => data.append(k, String(v))); try { const created = await uploadFormData('/video/generate', data); setJob(created); setSelected(created); toast.success('Video job queued.'); loadJobs(); } catch (err) { toast.error(err.message); } }
  async function action(type, item = job) { try { if (type === 'delete' && !window.confirm('Delete this video and its private files?')) return; if (type === 'delete') { await apiDelete(`/video/jobs/${item.id}`); if (job?.id === item.id) { setJob(null); releasePreview(); } } else { const next = await apiPost(`/video/jobs/${item.id}/${type}`); setJob(next); setSelected(next); } loadJobs(); } catch (e) { toast.error(e.message); } }
  async function patch(item, changes) { try { const next = await apiPatch(`/video/jobs/${item.id}`, changes); setJobs((old) => old.map((x) => x.id === next.id ? next : x)); if (selected?.id === next.id) setSelected(next); } catch (e) { toast.error(e.message); } }
  async function open(item) { setJob(item); setSelected(item); if (item.status === 'completed') await loadPreview(item); }
  async function download(item) { try { const blob = await apiGet(`/video/results/${item.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${item.title || 'lumina-video'}.${item.output_mime_type === 'image/gif' ? 'gif' : 'mp4'}`; a.click(); URL.revokeObjectURL(url); } catch (e) { toast.error(e.message); } }
  const current = selected || job;
  const capabilities = providerInfo?.providers?.find((item) => item.name === providerInfo.active)?.capabilities;
  const supportedModes = capabilities?.modes || MODES.map(([key]) => key);
  const supportedDurations = capabilities?.durations || [3, 5, 8];
  const supportedAspects = capabilities?.aspect_ratios || ['16:9', '9:16'];
  const supportedResolutions = capabilities?.resolutions || ['720p', '1080p', '4K'];
  return <div className="h-full overflow-y-auto bg-ink-950" data-testid="video-studio-page"><div className="max-w-[1500px] mx-auto p-6 lg:p-10 space-y-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-gold text-xs tracking-[.25em] uppercase flex gap-2 items-center"><Film className="w-4" />LUMINA Motion</p><h1 className="font-display text-4xl text-white mt-2">Video Studio</h1><p className="text-white/45 mt-2">Generate, manage, and refine every video from one private workspace.</p></div><span className="text-xs text-gold border border-gold/30 bg-gold/10 rounded-full px-3 py-1">Mock engine · no credentials</span></header>
    <div className="grid xl:grid-cols-[minmax(0,1fr)_minmax(380px,.8fr)] gap-6"><form onSubmit={generate} className="lumina-glass rounded-xl p-5 space-y-5"><div className="flex flex-wrap gap-2">{MODES.map(([key, name]) => <button key={key} type="button" onClick={() => { setMode(key); setFiles([]); }} className={`text-xs px-3 py-2 rounded ${mode === key ? 'bg-gold text-black' : 'bg-white/5 text-white/60 hover:bg-white/10'}`}>{name}</button>)}</div>
      {sourceRequired && <label className="block border border-dashed border-white/15 hover:border-gold/50 rounded-lg p-5 cursor-pointer text-center"><Upload className="w-5 text-gold mx-auto mb-2" /><span className="text-sm text-white/70">{mode === 'multi-image' || mode === 'interpolation' ? 'Add up to 8 source images' : 'Add source image'}</span><p className="text-xs text-white/35 mt-1">{files.length ? files.map((f) => f.name).join(', ') : 'PNG, JPEG, WebP · 15 MB each'}</p><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" multiple={mode === 'multi-image' || mode === 'interpolation'} onChange={(e) => choose(e.target.files)} /></label>}
      <label className="block text-xs text-white/60">Describe the video<textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} required maxLength="800" rows="3" className="mt-2 w-full rounded bg-black/40 border border-white/10 p-3 text-sm text-white" placeholder="Describe subject, movement, and scene…" /></label>
      <div className="grid sm:grid-cols-3 gap-3"><Select label="Duration" value={duration} onChange={setDuration} options={supportedDurations} /><Select label="Format" value={aspect} onChange={setAspect} options={supportedAspects} /><Select label="Resolution" value={resolution} onChange={setResolution} options={supportedResolutions} /></div>
      <button type="button" onClick={() => setAdvanced(!advanced)} className="text-xs text-gold">{advanced ? 'Hide' : 'Show'} advanced settings</button>{advanced && <div className="grid sm:grid-cols-2 gap-3 rounded-lg bg-black/25 p-4"><label className="text-xs text-white/60">Negative prompt<input value={negative} onChange={(e) => setNegative(e.target.value)} className="mt-1 w-full rounded bg-black/40 border border-white/10 p-2 text-white" /></label><Select label="FPS" value={fps} onChange={setFps} options={[12,24,30,60]} /><Select label="Quality" value={quality} onChange={setQuality} options={['draft','standard','high']} /><Select label="Camera motion" value={camera} onChange={setCamera} options={['auto','push-in','pan','orbit']} /><Select label="Style" value={style} onChange={setStyle} options={['cinematic','natural','editorial']} /><label className="text-xs text-white/60">Seed<input value={seed} onChange={(e) => setSeed(e.target.value)} inputMode="numeric" className="mt-1 w-full rounded bg-black/40 border border-white/10 p-2 text-white" /></label><Select label="Queue priority" value={priority} onChange={setPriority} options={[-1,0,1]} /></div>}
      <button className="w-full bg-gold text-black rounded py-3 font-medium text-sm flex justify-center gap-2"><Sparkles className="w-4" />Generate video</button></form>
      <section className="lumina-glass rounded-xl p-5 min-h-[430px]"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-white/40">Preview</p><h2 className="font-display text-2xl text-white">{current?.title || 'Ready when you are'}</h2></div>{current?.status === 'completed' && <button onClick={() => download(current)} className="text-gold"><Download /></button>}</div><div className="mt-5 min-h-[300px] bg-black/50 rounded flex items-center justify-center overflow-hidden">{ACTIVE.has(current?.status) && <div className="w-2/3 text-center"><Loader2 className="animate-spin text-gold mx-auto mb-3" /><p className="text-sm text-white capitalize">{label(current.status)}</p><div className="h-2 bg-white/10 rounded mt-4"><div className="h-full bg-gold rounded" style={{width:`${current.progress || 0}%`}} /></div><p className="text-xs text-white/40 mt-2">{current.progress || 0}% · about {current.estimated_seconds_remaining ?? 'a few'} seconds</p><button onClick={() => action('cancel', current)} className="mt-4 text-xs text-red-300">Cancel</button></div>}{current?.status === 'completed' && preview && (current.output_mime_type === 'image/gif' ? <img src={preview} alt="Generated video" className="max-h-[420px] max-w-full object-contain" /> : <video src={preview} controls className="max-h-[420px] max-w-full" />)}{['failed','cancelled'].includes(current?.status) && <div className="text-center"><p className="text-red-200 text-sm">{current.error || `Job ${current.status}`}</p><button onClick={() => action('retry', current)} className="mt-3 text-gold text-sm">Retry</button></div>}{!current && <Play className="text-white/30" />}</div>{current && <p className="text-xs text-white/40 mt-3">{label(current.mode)} · {current.duration_seconds}s · {current.resolution} · {current.aspect_ratio} · {current.provider} · {date(current.created_at)}</p>}</section></div>
    <section className="space-y-4"><div className="flex flex-wrap gap-3 items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-white/40">Video library</p><h2 className="font-display text-2xl text-white">Recent creations</h2></div><div className="flex gap-2"><button onClick={() => setView('grid')} className={view==='grid'?'text-gold':'text-white/40'}><Grid2X2 /></button><button onClick={() => setView('list')} className={view==='list'?'text-gold':'text-white/40'}><List /></button></div></div><div className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-2 top-2 w-4 text-white/35" /><input value={filters.search} onChange={(e)=>setFilters({...filters,search:e.target.value})} placeholder="Search videos" className="pl-8 py-2 rounded bg-white/5 border border-white/10 text-sm text-white" /></label><select value={filters.status} onChange={(e)=>setFilters({...filters,status:e.target.value})} className="bg-white/5 border border-white/10 rounded text-sm text-white px-2"><option value="">All statuses</option>{['queued','preparing','uploading','processing','rendering','completed','failed','cancelled'].map((x)=><option key={x}>{x}</option>)}</select><select value={filters.sort} onChange={(e)=>setFilters({...filters,sort:e.target.value})} className="bg-white/5 border border-white/10 rounded text-sm text-white px-2"><option value="recent">Recent</option><option value="title">Title</option><option value="favorite">Favorites first</option></select><button onClick={()=>setFilters({...filters,favorite:!filters.favorite})} className={`px-3 rounded text-sm ${filters.favorite?'bg-gold text-black':'bg-white/5 text-white/60'}`}>Favorites</button></div>
      {loading ? <div className="py-12 text-center text-white/40"><Loader2 className="animate-spin mx-auto" /></div> : !jobs.length ? <div className="py-12 text-center rounded border border-white/10 text-white/40">No videos match this view.</div> : <div className={view==='grid'?'grid md:grid-cols-2 xl:grid-cols-3 gap-3':'space-y-2'}>{jobs.map((item)=><article key={item.id} className={`border border-white/10 bg-white/[.025] rounded p-4 ${view==='list'?'flex items-center justify-between gap-3':''}`}><div className="min-w-0"><button onClick={()=>open(item)} className="text-left text-white text-sm truncate max-w-full">{item.title || item.prompt}</button><p className="text-xs text-white/40 mt-1 capitalize">{item.status} · {label(item.mode)} · {item.duration_seconds}s · {item.resolution}</p></div><div className="flex gap-2 mt-3"><button onClick={()=>patch(item,{favorite:!item.favorite})} title="Favorite" className={item.favorite?'text-gold':'text-white/40'}><Heart className="w-4" fill={item.favorite?'currentColor':'none'} /></button><button onClick={()=>{const title=window.prompt('Video title',item.title); if(title!==null)patch(item,{title});}} title="Rename" className="text-white/40"><Pencil className="w-4" /></button><button onClick={()=>action('duplicate',item)} title="Duplicate" className="text-white/40"><Copy className="w-4" /></button>{item.status==='completed'&&<button onClick={()=>download(item)} title="Download" className="text-gold"><Download className="w-4" /></button>}<button onClick={()=>action('delete',item)} title="Delete" className="text-red-300"><Trash2 className="w-4" /></button></div></article>)}</div>}</section>
  </div></div>;
}
function Select({label: text,value,onChange,options}) { return <label className="text-xs text-white/60">{text}<select value={value} onChange={(e)=>onChange(typeof options[0]==='number'?Number(e.target.value):e.target.value)} className="mt-1 w-full rounded bg-black/40 border border-white/10 p-2 text-white">{options.map((x)=><option key={x} value={x}>{x}</option>)}</select></label>; }

export function OrganizationActions({ selected, facets = { folders: [], collections: [] }, onPatch, onRefresh }) {
  const create = async (kind) => { const name = window.prompt(`New ${kind} name`); if (!name?.trim()) return; await apiPost('/video/library/organizations', { kind, name: name.trim() }); onRefresh(); };
  const rename = async (item) => { const name = window.prompt(`Rename ${item.kind}`, item.name); if (name?.trim()) { await apiPatch(`/video/library/organizations/${item.id}`, { name: name.trim() }); onRefresh(); } };
  return <div className="flex flex-wrap gap-2"><button type="button" onClick={() => create('folder')}>New folder</button><button type="button" onClick={() => create('collection')}>New collection</button>{(facets.folders || []).map((item) => <button type="button" key={item.id} onClick={() => selected && onPatch(selected, { folder: item.id })}>{item.name}</button>)}{(facets.collections || []).map((item) => <button type="button" key={item.id} onClick={() => selected && onPatch(selected, { collection_ids: [...new Set([...(selected.collection_ids || []), item.id])] })}>{item.name}</button>)}{(facets.folders || []).concat(facets.collections || []).map((item) => <button type="button" key={`rename-${item.id}`} onClick={() => rename(item)}>Rename {item.name}</button>)}</div>;
}
