from pathlib import Path

ROOT = Path.cwd()
TARGET = ROOT / "backend" / "code_builder" / "ollama_service.py"
TEST = ROOT / "backend" / "tests" / "test_code_builder_ollama_event_loop.py"

text = TARGET.read_text(encoding="utf-8")

old_init = '''        self._owns_client = client is None\n        self._closed = False\n\n        if client is None:\n            self._client = httpx.AsyncClient(\n                base_url=self.configuration.base_url,\n                timeout=self.configuration.timeouts.to_httpx_timeout(),\n                verify=self.configuration.verify_tls,\n                follow_redirects=(\n                    self.configuration.follow_redirects\n                ),\n                headers={\n                    "Accept": "application/json",\n                    "Content-Type": "application/json",\n                    "User-Agent": self.configuration.user_agent,\n                },\n                limits=httpx.Limits(\n                    max_connections=20,\n                    max_keepalive_connections=10,\n                    keepalive_expiry=30.0,\n                ),\n                trust_env=False,\n            )\n        else:\n            self._client = client\n'''

new_init = '''        # A production-owned AsyncClient must not be shared across the\n        # short-lived event loops created by the Code Builder worker.\n        # HTTPX transports are loop-bound after first use; reusing one from a\n        # later asyncio.run(...) causes RuntimeError: Event loop is closed.\n        # Keep injected clients for tests/integrations, but create owned\n        # clients per request inside the active event loop.\n        self._owns_client = client is None\n        self._closed = False\n        self._client = client\n'''

if old_init in text:
    text = text.replace(old_init, new_init, 1)
elif "create owned\n        # clients per request" not in text:
    raise SystemExit("OllamaService __init__ anchor not found; refusing unsafe patch")

old_close = '''        if self._owns_client:\n            await self._client.aclose()\n\n    async def _sleep_before_retry(\n'''
new_close = '''        # Owned clients are request-scoped and are closed in _request_json.\n        # An injected client is externally owned and must not be closed here.\n\n    def _build_owned_client(self) -> httpx.AsyncClient:\n        """Create a request-scoped client bound to the current event loop."""\n\n        return httpx.AsyncClient(\n            base_url=self.configuration.base_url,\n            timeout=self.configuration.timeouts.to_httpx_timeout(),\n            verify=self.configuration.verify_tls,\n            follow_redirects=self.configuration.follow_redirects,\n            headers={\n                "Accept": "application/json",\n                "Content-Type": "application/json",\n                "User-Agent": self.configuration.user_agent,\n            },\n            limits=httpx.Limits(\n                max_connections=20,\n                max_keepalive_connections=10,\n                keepalive_expiry=30.0,\n            ),\n            trust_env=False,\n        )\n\n    async def _sleep_before_retry(\n'''
if old_close in text:
    text = text.replace(old_close, new_close, 1)
elif "def _build_owned_client" not in text:
    raise SystemExit("OllamaService close anchor not found; refusing unsafe patch")

old_request_start = '''        last_exception: BaseException | None = None\n\n        for attempt in range(maximum_attempts):\n            try:\n                response = await self._client.request(\n'''
new_request_start = '''        last_exception: BaseException | None = None\n        owned_client = self._build_owned_client() if self._owns_client else None\n        client = owned_client if owned_client is not None else self._client\n        if client is None:\n            raise OllamaServiceError("No Ollama HTTP client is available.")\n\n        try:\n            for attempt in range(maximum_attempts):\n                try:\n                    response = await client.request(\n'''
if old_request_start in text:
    text = text.replace(old_request_start, new_request_start, 1)
elif "owned_client = self._build_owned_client()" not in text:
    raise SystemExit("_request_json start anchor not found; refusing unsafe patch")

# Re-indent the body of the retry loop and add request-scoped close. We target
# the exact tail of _request_json so unrelated methods are untouched.
old_tail = '''            except asyncio.CancelledError as exc:\n                raise OllamaRequestCancelledError(\n                    "The Ollama request was cancelled."\n                ) from exc\n\n            except httpx.TimeoutException as exc:\n                last_exception = exc\n\n                if attempt + 1 < maximum_attempts:\n                    LOGGER.warning(\n                        "Ollama request to %s timed out; retrying.",\n                        endpoint.value,\n                    )\n\n                    await self._sleep_before_retry(\n                        attempt\n                    )\n                    continue\n\n                raise OllamaTimeoutError(\n                    "Ollama did not respond before the configured timeout "\n                    f"for endpoint {endpoint.value}."\n                ) from exc\n\n            except (\n                httpx.ConnectError,\n                httpx.NetworkError,\n                httpx.RemoteProtocolError,\n                httpx.LocalProtocolError,\n            ) as exc:\n                last_exception = exc\n\n                if attempt + 1 < maximum_attempts:\n                    LOGGER.warning(\n                        "Ollama connection failure for %s; retrying: %s",\n                        endpoint.value,\n                        exc,\n                    )\n\n                    await self._sleep_before_retry(\n                        attempt\n                    )\n                    continue\n\n                raise OllamaUnavailableError(\n                    "Cannot connect to the local Ollama service at "\n                    f"{self.configuration.base_url}. Ensure Ollama is "\n                    "running and listening on the configured address."\n                ) from exc\n\n            except httpx.RequestError as exc:\n                last_exception = exc\n\n                if attempt + 1 < maximum_attempts:\n                    LOGGER.warning(\n                        "Ollama transport error for %s; retrying: %s",\n                        endpoint.value,\n                        exc,\n                    )\n\n                    await self._sleep_before_retry(\n                        attempt\n                    )\n                    continue\n\n                raise OllamaUnavailableError(\n                    f"Ollama request failed for {endpoint.value}: {exc}"\n                ) from exc\n\n        raise OllamaUnavailableError(\n            "Ollama request failed after all retry attempts."\n        ) from last_exception\n'''

new_tail = '''                except asyncio.CancelledError as exc:\n                    raise OllamaRequestCancelledError(\n                        "The Ollama request was cancelled."\n                    ) from exc\n\n                except httpx.TimeoutException as exc:\n                    last_exception = exc\n\n                    if attempt + 1 < maximum_attempts:\n                        LOGGER.warning(\n                            "Ollama request to %s timed out; retrying.",\n                            endpoint.value,\n                        )\n                        await self._sleep_before_retry(attempt)\n                        continue\n\n                    raise OllamaTimeoutError(\n                        "Ollama did not respond before the configured timeout "\n                        f"for endpoint {endpoint.value}."\n                    ) from exc\n\n                except (\n                    httpx.ConnectError,\n                    httpx.NetworkError,\n                    httpx.RemoteProtocolError,\n                    httpx.LocalProtocolError,\n                ) as exc:\n                    last_exception = exc\n\n                    if attempt + 1 < maximum_attempts:\n                        LOGGER.warning(\n                            "Ollama connection failure for %s; retrying: %s",\n                            endpoint.value,\n                            exc,\n                        )\n                        await self._sleep_before_retry(attempt)\n                        continue\n\n                    raise OllamaUnavailableError(\n                        "Cannot connect to the local Ollama service at "\n                        f"{self.configuration.base_url}. Ensure Ollama is "\n                        "running and listening on the configured address."\n                    ) from exc\n\n                except httpx.RequestError as exc:\n                    last_exception = exc\n\n                    if attempt + 1 < maximum_attempts:\n                        LOGGER.warning(\n                            "Ollama transport error for %s; retrying: %s",\n                            endpoint.value,\n                            exc,\n                        )\n                        await self._sleep_before_retry(attempt)\n                        continue\n\n                    raise OllamaUnavailableError(\n                        f"Ollama request failed for {endpoint.value}: {exc}"\n                    ) from exc\n\n            raise OllamaUnavailableError(\n                "Ollama request failed after all retry attempts."\n            ) from last_exception\n        finally:\n            if owned_client is not None:\n                await owned_client.aclose()\n'''

if old_tail in text:
    text = text.replace(old_tail, new_tail, 1)
elif "if owned_client is not None:\n                await owned_client.aclose()" not in text:
    raise SystemExit("_request_json tail anchor not found; refusing unsafe patch")

TARGET.write_text(text, encoding="utf-8")

TEST.write_text('''import asyncio\nfrom unittest.mock import patch\n\nimport httpx\n\nfrom backend.code_builder.ollama_service import OllamaService\n\n\ndef test_owned_http_client_is_recreated_across_event_loops():\n    created = []\n\n    class FakeAsyncClient:\n        def __init__(self, *args, **kwargs):\n            self.loop = None\n            self.closed = False\n            created.append(self)\n\n        async def request(self, **kwargs):\n            loop = asyncio.get_running_loop()\n            if self.loop is None:\n                self.loop = loop\n            elif self.loop is not loop:\n                raise RuntimeError("Event loop is closed")\n            return httpx.Response(200, json={"version": "test"})\n\n        async def aclose(self):\n            self.closed = True\n\n    service = OllamaService()\n    with patch("backend.code_builder.ollama_service.httpx.AsyncClient", FakeAsyncClient):\n        assert asyncio.run(service.get_version()) == "test"\n        assert asyncio.run(service.get_version()) == "test"\n\n    assert len(created) == 2\n    assert all(client.closed for client in created)\n    assert created[0].loop is not created[1].loop\n''', encoding="utf-8")

print("FINAL_EVENT_LOOP_PATCH_APPLIED")
